from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/alley-finish-244';C=O/'comparison';C.mkdir(exist_ok=True)
for label,path in [('before',R/'art/studies/final-geometry-242/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96);
 for name,box in [('footing',(600,1250,1170,1660)),('roof',(1080,130,1450,500)),('windows',(2480,70,2820,640)),('arcade',(1430,870,2450,1280))]:im.crop(box).save(C/(label+'-'+name+'.png'))
assert (C/'before-full.jpg').read_bytes()!=(C/'after-full.jpg').read_bytes()
b=np.asarray(Image.open(O/'main-4k.png').convert('RGB'));checks={}
for row in json.loads((R/'art/studies/pixel-characters-217/assets.json').read_text()):
 target=np.asarray(Image.open(R/row['placed_canvas']).convert('RGBA'));mask=target[:,:,3]==255;assert np.array_equal(b[mask],target[:,:,:3][mask]);checks[row['name']]='exact'
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
(R/'prototype/review-244.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>244 · Alley finish</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:1500px;margin:auto;padding:24px}h1{font-size:25px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;margin:18px auto}#footing{max-width:1000px}#roof,#windows{max-width:700px}a{color:#e8c8a4}</style><main><h1>244 · Alley finish</h1><p>Compact blue-grey weathered footing with pipe-entry seals; chipped and weathered left roof edge; varied staining across the right dark-building window bank; quieter tunnel interiors. The warm building windows and accepted haze are preserved.</p><button onclick="choose('before')">Before · 242</button><button onclick="choose('after')">Alley refinements · 244</button><h2>Shared footing</h2><img id="footing" alt="Compact weathered footing comparison"><h2>Left roof edge</h2><img id="roof" alt="Weathered chipped roof edge"><h2>Window bank</h2><img id="windows" alt="Varied weathering on the dark building window bank"><h2>Ground arcade</h2><img id="arcade" alt="Quiet tunnel interiors through retained haze"><h2>Whole scene</h2><img id="full" alt="Whole scene"><p><a href="../art/studies/alley-finish-244/main-4k.png">Full-resolution scene</a> · <a href="../art/studies/alley-finish-244/scene.blend">Editable scene</a></p></main><script>function choose(v){document.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===(v==='before'?0:1)));for(let id of ['footing','full','roof','windows','arcade'])document.getElementById(id).src='../art/studies/alley-finish-244/comparison/'+v+'-'+id+(id==='full'?'.jpg':'.png')+'?v=244-final';location.hash=v}function sync(){choose(location.hash==='#before'?'before':'after')}addEventListener('hashchange',sync);sync()</script></html>''')
print('244 published; exact characters verified')
