from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/arcade-tunnels-220';C=O/'comparison';C.mkdir(exist_ok=True)
a=json.loads((O/'audit.json').read_text());row=a['objects'][0]
# Copy the measured side/profile diagram derived from the native tunnel audit.
import shutil
shutil.copy2(O/'measured-route.svg',C/'route.svg')
for label,path in [('before',R/'art/studies/haze-texture-219/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.crop((1250,760,2630,1320)).save(C/(label+'-arcade.png'));im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96)
(R/'prototype/review-220.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>220 · Descending arcade tunnels</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}header,main{max-width:1400px;margin:auto;padding:20px}h1{font-size:24px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto}a{color:#e8c8a4;display:inline-block;margin:12px 18px 12px 0}.route{max-width:900px;margin:20px auto}</style><header><h1>220 · Descending arcade tunnels</h1><p>Every ground-level arch now connects to a 30 m straight tunnel, followed by 30 m descending at 45°. All 18 tunnels use the existing arch openings; the previous two side-turning tunnels are removed from view. Both images include the textured-haze study and selected characters.</p><button onclick="choose('before',this)">Previous two tunnels</button><button class="active" onclick="choose('after',this)">18 descending tunnels</button></header><main><img id="detail" src="../art/studies/arcade-tunnels-220/comparison/after-arcade.png" alt="Ground arcade tunnel comparison"><p><a href="../art/studies/arcade-tunnels-220/main-4k.png">Full-resolution image</a><a href="../art/studies/arcade-tunnels-220/scene.blend">Editable scene</a><a href="review-219.html">Haze comparison</a><a href="review-218.html">Sun comparison</a></p><img class="route" src="../art/studies/arcade-tunnels-220/comparison/route.svg" alt="Side diagram: 30 m straight, then 30 m down at 45 degrees"><img id="full" src="../art/studies/arcade-tunnels-220/comparison/after-full.jpg" alt="Full scene with all descending tunnels"></main><script>function choose(v,b){document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let p='../art/studies/arcade-tunnels-220/comparison/'+v;document.getElementById('detail').src=p+'-arcade.png';document.getElementById('full').src=p+'-full.jpg';location.hash=v}if(location.hash==='#before')choose('before',document.querySelectorAll('button')[0]);</script></html>''')
print('220 comparison published')
