"""Pure planning builder: emits bounded authored-coordinate features; does not edit Blender scenes."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-119'
def build_feature_plan(inventory):
 families={
 'low_intact':{'intent':'Broad intact low attic masonry; unequal shallow inset fields, one restrained blind niche where support exists, no added through-hole.','panels':'Two differently proportioned side fields below existing square aperture head; margins and whole-course bases continuous.','damage':'None by default. Existing crown remains the main damage.'},
 'tall_ordered':{'intent':'Taller surviving attic mass with narrow pilaster strips and vertically biased recessed field, sparse blind slit rather than new window array.','panels':'Retain broad blank masonry, one principal field and subordinate shorter field. Existing aperture retained.','damage':'Only selected shallow facing loss, with connected trim interruption; no extra true breach.'},
 'eroded_transition':{'intent':'Descending crown transition: interrupted shallow field molding reflects surviving masonry rather than imposing a complete symmetric frame.','panels':'One broad shallow field below intact high shoulder, shorter plain panel under low end; no freestanding framing.','damage':'One localized connected edge/trim loss; preserve bearing and crown silhouette.'}}
 specs={
 5:('tall_ordered',[[-5,-1.8,60.0,67.2],[1.8,4.85,60.0,64.6]],[-3.55,61.0,64.0],{'kind':'shallow facing and upper field trim loss','u_z_center':[3.8,64.75],'u_z_radius':[.62,.85],'radial_depth_max':.85,'through':False}),
 6:('low_intact',[[-4.9,-1.7,60.0,64.3],[1.8,4.7,60.0,63.8]],[-3.0,60.6,62.5],None),
 7:('low_intact',[[-4.8,-1.75,59.9,63.8],[1.7,4.8,60.3,63.8]],None,None),
 9:('tall_ordered',[[-4.85,-1.7,60.0,69.4],[1.8,4.6,60.0,68.3]],[-3.4,63.0,66.6],None),
 11:('eroded_transition',[[-4.85,-1.75,60.0,66.9],[1.8,4.7,60.0,63.7]],None,{'kind':'edge loss connecting field border to entablature','u_z_center':[3.6,64.8],'u_z_radius':[.72,.68],'radial_depth_max':1.15,'through':False}),
 12:('low_intact',[[-4.7,-1.85,60.15,63.7],[1.65,4.85,60.15,64.0]],None,None)}
 plans=[]
 for b in inventory['bays']:
  j=b['bay'];family,fields,niche,damage=specs[j]
  plans.append({'bay':j,'family':family,'authored_wall_z_bounds':b['authored_z_range'],'fields_u0_u1_z0_z1':fields,'blind_niche_center_u_bottom_top':niche,'blind_niche_width_m':.65 if j==9 else .9,'field_recess_depth_m':.28 if family=='low_intact'else .38,'pilaster_width_m':.25 if family=='low_intact'else .32,'pilaster_projection_m':.28,'planned_damage':damage,'main_visible_samples':b['previous_main_visibility']['counts'].get('visible',0),'layout_status':'Proposed coordinates require exact local wall support and camera ray checks before any construction.'})
 return {'status':'Inventory and parameterization only. Await119 painted critic before scene edits.','source':'116 approved global geometry, carrying accepted119 bay8 only after review.','references':['UCL-01','UCL-02','DP-03'],'families':families,'bays':plans,'damage_distribution':{'existing_119_through_breach':8,'new_shallow_connected_sites':[5,11],'additional_through_holes':0,'broad_intact_bays':[6,7,9,12]},'parameterization':{'mapping':'Explicit j replaces bay8 center angle; same original author coordinates, angular compression.68, inner radial.55, E affine and116+4degree yaw. Do not copy or rotate deformed bay8 meshes.','features':'prism/box/safe_support/cut helpers become a BayBuilder(j, source116_transform, source_materials); each feature receives authored bounds and stable seed. New meshes receive source-world position, damage proximity, role/bay/tier/feature metadata.','masking':'Distance-to-precut-surface labels only new recess/core faces; preserve existing FACE masks and POINT original-world coordinates.','damage':'No generic radial-star cutter. Each selected shallow loss has asymmetric course-led contour and short nonparallel depth returns.119 breach remains sole new sky hole.','guards':['Exact wall support at all frame segment corners and midpoint; omit unsupported segments.','Damage cutter box and untouched original vertex surface distance checks; reject destructive Booleans.','Preserve original front crown mesh outside selected damage; no wholewall regeneration.','Retain original square apertures and major tower profiles.','Ray-check main-camera visibility and physical cavity depth before detail spread.','Confirm all locked non-landmark objects/materials unchanged.'],'repeat_control':'Distinct field proportions and heights, niche only3of6bays, no repeating breach. Shorten/suppress fields against actual surviving wall; never extrapolate coarse0.5m inventory as exact geometry.'}}
if __name__=='__main__':
 inventory=json.loads((O/'assembly-inventory.json').read_text());plan=build_feature_plan(inventory);(O/'assembly-feature-plan.json').write_text(json.dumps(plan,indent=2));print('Planned',len(plan['bays']),'bays; no scene edits')
