"""Scope and preserve all locked scene systems for129 user-requested architecture."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
source=(R/'tools/coliseum_lighting_validate_128.py').read_text().split('\nbefore,bm=snapshot(')[0];exec(source)
before,bm=snapshot(R/'art/studies/coliseum-128/scene.blend');bg=cloud_geometry();bw=protected_world();bp=selected_pipe_dimensions();bl=landmark_geometry();lights={o.name:digest([o.data.type,o.data.energy,tuple(o.data.color),[tuple(r)for r in o.matrix_world]])for o in bpy.context.scene.objects if o.type=='LIGHT'}
after,am=snapshot(R/'art/studies/coliseum-129/scene.blend');ag=cloud_geometry();aw=protected_world();ap=selected_pipe_dimensions();al=landmark_geometry();lights2={o.name:digest([o.data.type,o.data.energy,tuple(o.data.color),[tuple(r)for r in o.matrix_world]])for o in bpy.context.scene.objects if o.type=='LIGHT'}
audit=json.loads((R/'art/studies/coliseum-129/generation.json').read_text());allowed={r['name']for r in audit['arches']['walls_and_parts']}|{'COL127 T2 continuous arcade wall'}|{f"COL110 Tower{r['tower']} core"for r in audit['pillars']['towers']if r.get('accepted')};removed=set(audit['pillars']['removed_old_long_panel_sills'])|{r['object']for r in audit['cornice_clearance']['removed']};added=set(audit['pillars']['new_matching_sills'])
changes={k for k,v in bl.items()if al.get(k)!=v};unexpected=changes-allowed-removed
r={'source':'128','candidate':'129','nonlandmark_objects_compared':len(before),'changed_nonlandmark_objects':[k for k,v in before.items()if after.get(k)!=v],'added_nonlandmark_objects':sorted(set(after)-set(before)),'changed_nonlandmark_materials':[k for k,v in bm.items()if am.get(k)!=v],'added_nonlandmark_materials':sorted(set(am)-set(bm)),'landmark_objects_compared':len(bl),'authorized_changed_landmark_objects':sorted(changes&allowed),'authorized_removed_landmark_objects':sorted(changes&removed),'unexpected_landmark_geometry_changes':sorted(unexpected),'unexpected_added_landmark_objects':sorted(set(al)-set(bl)-added),'clouds_unchanged':bg==ag,'world_unchanged':bw==aw,'lights_unchanged':lights==lights2,'pipe_unchanged':bp==ap,'scope':'User arch/pillar/dentil edits, clean B10 foundation, and rebuilt landmark contact ink only.'}
(R/'art/studies/coliseum-129/preservation.json').write_text(json.dumps(r,indent=2));assert all(not r[k]for k in ['changed_nonlandmark_objects','added_nonlandmark_objects','changed_nonlandmark_materials','added_nonlandmark_materials','unexpected_landmark_geometry_changes','unexpected_added_landmark_objects']);assert all(r[k]for k in ['clouds_unchanged','world_unchanged','lights_unchanged','pipe_unchanged']);bpy.data.libraries.write(str(R/'art/studies/coliseum-129/kit.blend'),{bpy.data.collections['110 Coliseum detailed front ruin']},fake_user=True);print('129 preservation passed',len(before),len(bl))
