from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/crack-lift-258';C=O/'comparison';C.mkdir(exist_ok=True)
a=Image.open(R/'art/studies/soil-panel-257/main-4k.png').convert('RGB').crop((50,1120,330,1660));b=Image.open(O/'detail.png').convert('RGB');assert b.size==a.size,(a.size,b.size)
a.save(C/'before.png');b.save(C/'after.png');assert a.tobytes()!=b.tobytes()
g=Image.new('L',(560,540));g.paste(a.convert('L'),(0,0));g.paste(b.convert('L'),(280,0));g.save(O/'grayscale.png')
(R/'prototype/review-258.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>258 · Raised crack</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:900px;margin:auto;padding:24px}h1{font-size:25px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;max-width:560px;height:auto;margin:18px auto}a{color:#e8c8a4}</style><main><h1>258 · Raised crack</h1><p>The crack sits above the spalling, leaving a clear gap. The damaged patch stays in place.</p><button onclick="choose('before')">Before · 257</button><button onclick="choose('after')">After · 258</button><img id="detail" alt="Native rendered close-up of the raised crack"><p>Native close-up at the existing scene camera.</p><p><a href="../art/studies/crack-lift-258/scene.blend">Editable scene with the change</a></p></main><script>function choose(v){document.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===(v==='before'?0:1)));document.getElementById('detail').src='../art/studies/crack-lift-258/comparison/'+v+'.png?v=258';location.hash=v}function sync(){choose(location.hash==='#before'?'before':'after')}addEventListener('hashchange',sync);sync()</script></html>''')
print('258 native detail published')
