from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/far-weathering-234';C=O/'comparison';C.mkdir(exist_ok=True)
for label,path in [('before',R/'art/studies/facade-finish-233/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.crop((2220,740,2630,1140)).save(C/(label+'-right.png'));im.crop((1100,650,2860,1490)).save(C/(label+'-street.png'));im.crop((1200,670,1800,1250)).save(C/(label+'-left.png'));im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96)
b=np.asarray(Image.open(O/'main-4k.png').convert('RGB'));checks={}
for row in json.loads((R/'art/studies/pixel-characters-217/assets.json').read_text()):
 target=np.asarray(Image.open(R/row['placed_canvas']).convert('RGBA'));mask=target[:,:,3]==255;assert np.array_equal(b[mask],target[:,:,:3][mask]);checks[row['name']]='exact'
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
(R/'prototype/review-234.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>234 · Larger stains and facade erosion</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:1500px;margin:auto;padding:24px}h1{font-size:25px}h2{font-size:20px;margin-top:36px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;margin:18px auto}#crown{max-width:600px}a{color:#e8c8a4}</style><main><h1>234 · Larger stains and facade erosion</h1><p>Larger tapering rain trails and broad warm light stains now break up the dark window surfaces. Native crumbled facade recesses and longer fractures add damage at a scale readable from the street view.</p><button onclick="choose('before',this)">Before · 233</button><button class="active" onclick="choose('after',this)">Updated scene · 234</button><img id="street" src="../art/studies/far-weathering-234/comparison/after-street.png" alt="Middle street comparison"><p><a href="../art/studies/far-weathering-234/main-4k.png">Full-resolution scene</a> · <a href="../art/studies/far-weathering-234/scene.blend">Editable scene</a> · <a href="../art/components/facades/v234/midground-buildings.blend">Updated prefab library</a></p><h2>Window stains and facade recesses</h2><img id="left" src="../art/studies/far-weathering-234/comparison/after-left.png" alt="Left building windows"><h2>Right facade damage</h2><img id="right" src="../art/studies/far-weathering-234/comparison/after-right.png" alt="Right window finish"><h2>Whole scene</h2><img id="full" src="../art/studies/far-weathering-234/comparison/after-full.jpg" alt="Whole scene"></main><script>function choose(v,b){document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');for(let id of ['street','left','right','full'])document.getElementById(id).src='../art/studies/far-weathering-234/comparison/'+v+'-'+id+(id==='full'?'.jpg':'.png');location.hash=v}</script></html>''')
print('234 published; characters exact')
