from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/footing-243';C=O/'comparison';C.mkdir(exist_ok=True)
for label,path in [('before',R/'art/studies/final-geometry-242/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96);im.crop((600,1250,1170,1660)).save(C/(label+'-footing.png'))
assert (C/'before-full.jpg').read_bytes()!=(C/'after-full.jpg').read_bytes()
b=np.asarray(Image.open(O/'main-4k.png').convert('RGB'));checks={}
for row in json.loads((R/'art/studies/pixel-characters-217/assets.json').read_text()):
 target=np.asarray(Image.open(R/row['placed_canvas']).convert('RGBA'));mask=target[:,:,3]==255;assert np.array_equal(b[mask],target[:,:,:3][mask]);checks[row['name']]='exact'
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
(R/'prototype/review-243.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>243 · Compact weathered footing</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:1500px;margin:auto;padding:24px}h1{font-size:25px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;margin:18px auto}#footing{max-width:1000px}a{color:#e8c8a4}</style><main><h1>243 · Compact weathered footing</h1><p>A smaller shared footing under the two ground-entry services, beyond the pipe loop. Cool blue-grey mineral, stronger weathering, chipped edges and dark contact seals. The rest of the scene retains 242.</p><button onclick="choose('before')">Before · 242</button><button onclick="choose('after')">Revised footing · 243</button><img id="footing" alt="Compact weathered footing comparison"><img id="full" alt="Whole scene"><p><a href="../art/studies/footing-243/main-4k.png">Full-resolution scene</a> · <a href="../art/studies/footing-243/scene.blend">Editable scene</a></p></main><script>function choose(v){document.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===(v==='before'?0:1)));for(let id of ['footing','full'])document.getElementById(id).src='../art/studies/footing-243/comparison/'+v+'-'+id+(id==='full'?'.jpg':'.png')+'?v=243-final';location.hash=v}function sync(){choose(location.hash==='#before'?'before':'after')}addEventListener('hashchange',sync);sync()</script></html>''')
print('243 published; exact characters verified')
