from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/midground-230';C=O/'comparison';C.mkdir(exist_ok=True)
for label,path in [('before',R/'art/studies/entry-surround-229/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.crop((1100,650,2860,1490)).save(C/(label+'-street.png'));im.crop((1200,670,1800,1250)).save(C/(label+'-left.png'));im.crop((1050,1060,2800,1550)).save(C/(label+'-walls.png'));im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96)
b=np.asarray(Image.open(O/'main-4k.png').convert('RGB'));checks={}
for row in json.loads((R/'art/studies/pixel-characters-217/assets.json').read_text()):
 target=np.asarray(Image.open(R/row['placed_canvas']).convert('RGBA'));mask=target[:,:,3]==255;assert np.array_equal(b[mask],target[:,:,:3][mask]);checks[row['name']]='exact'
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
(R/'prototype/review-230.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>230 · A more varied street</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:1500px;margin:auto;padding:24px}h1{font-size:25px}h2{font-size:20px;margin-top:36px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;margin:18px auto}a{color:#e8c8a4}</style><main><h1>230 · A more varied street</h1><p>Six additional buildings, varied entrances and windows, two broken panes, full-size service connections, rooftop equipment and heavier ruin weathering.</p><button onclick="choose('before',this)">Before · 229</button><button class="active" onclick="choose('after',this)">Updated street · 230</button><img id="street" src="../art/studies/midground-230/comparison/after-street.png" alt="Middle street comparison"><p><a href="../art/studies/midground-230/main-4k.png">Full-resolution scene</a> · <a href="../art/studies/midground-230/scene.blend">Editable scene</a> · <a href="../art/components/facades/v230/midground-buildings.blend">Building prefab library</a></p><h2>Windows and roof details</h2><img id="left" src="../art/studies/midground-230/comparison/after-left.png" alt="Left building windows"><h2>Broken walls and ink</h2><img id="walls" src="../art/studies/midground-230/comparison/after-walls.png" alt="Weathered transition walls"><h2>Top-down layout</h2><p>Measured footprints: twelve existing buildings plus six staggered additions. Heights vary by full storeys, with open passages retained between buildings.</p><img src="../art/studies/midground-230/top-down-plan.svg" alt="Measured before and after building footprints"><img src="../art/studies/midground-230/topdown-native.png" alt="Native overhead geometry study"><h2>Whole scene</h2><img id="full" src="../art/studies/midground-230/comparison/after-full.jpg" alt="Whole scene"></main><script>function choose(v,b){document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');for(let id of ['street','left','walls','full'])document.getElementById(id).src='../art/studies/midground-230/comparison/'+v+'-'+id+(id==='full'?'.jpg':'.png');location.hash=v}</script></html>''')
print('230 published; characters exact')
