from pathlib import Path
R=Path('/PATH/TO/transmissions-from-alpha-centauri');P=R/'prototype';a='/art/reviews/xenon-059/'
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}p{max-width:950px;color:#c9c1c9}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}button{padding:10px;background:#38313e;color:white;border:1px solid #79637a}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>059 · Connected concrete fractures</title><style>{css}</style><header><h1>059 · Connected concrete fractures</h1><p>Two local specimens in the existing alley: a right concrete support and a front-left sloped mineral column face. A adds independent cracks; B connects routes into a fracture network. The rest of the scene retains 058.</p><p><a href="#support">Support</a> · <a href="#panel">Panel</a> · <a href="{a}density.blend">A scene</a> · <a href="{a}network.blend">B scene</a> · <a href="review-058.html">058 baseline</a></p><button onclick="document.body.classList.toggle(\'gray\')">Toggle grayscale</button></header><section><h2>Unchanged game camera</h2><p>This is a two-component test, not a whole-alley rollout. The front-left column base is near the edge of the frame; use the closeups to inspect the paths, but judge their weight here.</p><div class="grid">'+fig(a+'density.png','A · Six independent anchored paths')+fig(a+'network.png','B · Six connected routes + junction breakouts')+'</div></section>'
for part in ['support','panel']:
 page+=f'<section id="{part}"><h2>{('Concrete support' if part=='support' else 'Mineral column face')} · native closeup</h2><div class="grid">'+fig(a+'density-'+part+'.png','A · Density-only control')+fig(a+'network-'+part+'.png','B · Connected, variable-width network')+'</div></section>'
page+='<section><h2>Reference</h2><div class="grid">'+fig('/references/user-concrete-crack-study/concrete-fracture-reference.png','User reference · fractures, seams and local loss')+fig('/art/reviews/xenon-051/reference-facade.png','Selected concept · architectural context')+'</div><p>B adds linked boundary-to-junction paths, varied aperture and three local breakouts. Cracks are shallow editable geometry cuts with dark recessed floors. Existing support spalls remain. The recessed panel was found to sit behind the solid column, so the second test uses the exposed mineral column face. This first network does not yet continue around corners or model structural stresses; a route count is not equivalent to total crack length.</p><p>References: UP-01, UP-03, DP-08 and the supplied concrete closeup. No reference image is projected onto these surfaces. Visual proof only: intersecting cuts still produce non-manifold junctions. Do not use this as a production geometry master yet. User review pending.</p></section></html>'
(P/'review-059.html').write_text(page);(P/'index.html').write_text(page)
