from pathlib import Path
import json
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/scene-weathering-195'
a=Image.open(O/'main-4k.png').convert('RGB');b=Image.open(R/'art/studies/rust-189/main-4k.png').convert('RGB')
boxes=json.loads((O/'framing.json').read_text());boxes.update({'left-building':[0,0,1440,2200],'portal-post':[610,960,800,1760],'ordinary-mounts':[530,190,750,750],'left-splice':[367,1355,667,1655],'ink':[300,100,570,800]})
for label,im in [('before',b),('after',a)]:
 im.resize((1800,round(im.height*1800/im.width)),Image.Resampling.LANCZOS).save(O/(label+'-display.png'))
 im.convert('L').resize((1200,round(im.height*1200/im.width)),Image.Resampling.LANCZOS).save(O/(label+'-gray.png'))
 for key,box in boxes.items():im.crop(box).save(O/(label+'-'+key+'.png'))
sections=''
for key,title in [('left-building','First building · moderate weathering'),('service-panel','Exposed services · lighter backing'),('portal-post','Service-bay frame post'),('left-beam','Left support · feathered edge rust'),('right-beam','Right support · half-strength rust'),('ordinary-mounts','Pipe plates · broader bolt-water stains'),('left-splice','Support plate · bolt-water stains'),('ink','Building corner · repaired ink')]:
 if key not in boxes:continue
 sections+=f'<section id="{key}"><h2>{title}</h2><div class="pair"><figure><img src="/art/studies/scene-weathering-195/before-{key}.png"><figcaption>189</figcaption></figure><figure><img src="/art/studies/scene-weathering-195/after-{key}.png"><figcaption>195</figcaption></figure></div></section>'
html='''<!doctype html><meta charset="utf-8"><title>195 · Alley weathering</title><style>body{max-width:1700px;margin:24px auto;background:#211f26;color:#ece6e0;font:16px system-ui}h1{font-size:30px}a{color:#f3b383}img{max-width:100%}#main{width:100%;display:block}button{padding:10px 18px;cursor:pointer;margin:6px}nav{line-height:2;padding:14px 0}.pair{display:flex;gap:24px;align-items:flex-start}.pair figure{flex:1;margin:0}.pair img{width:100%;max-height:1000px;object-fit:contain}figcaption{padding:8px}section{border-top:1px solid #514750;padding:28px 0}</style><h1>195 · Alley weathering</h1><p>Broader bolt-water stains, moderate wear across the first building, a lighter exposed-service backing, and inward-feathered edge rust. The right support has half the rust strength of the left. Both building-corner ink overruns are corrected.</p><nav><a href="#left-building">Building</a> · <a href="#service-panel">Services</a> · <a href="#left-beam">Beam rust</a> · <a href="#ordinary-mounts">Bolt trails</a> · <a href="#ink">Ink repair</a> · <a href="/prototype/review-190.html">Separate Colosseum crumbling study</a></nav><button onclick="pick('after')">195 updated</button><button onclick="pick('before')">189 before</button><img id="main" src="/art/studies/scene-weathering-195/after-display.png"><p><a href="/art/studies/scene-weathering-195/main-4k.png">Full 4K render</a> · <a href="/art/studies/scene-weathering-195/scene.blend">Editable scene</a></p>'''+sections+'''<details><summary>Grayscale</summary><div class="pair"><img width="48%" src="/art/studies/scene-weathering-195/before-gray.png"><img width="48%" src="/art/studies/scene-weathering-195/after-gray.png"></div></details><script>function pick(v){document.getElementById('main').src='/art/studies/scene-weathering-195/'+v+'-display.png'}</script>'''
(R/'prototype/review-195.html').write_text(html);(O/'crop-regions.json').write_text(json.dumps(boxes,indent=2))
