from pathlib import Path
from PIL import Image
import json,numpy as np
R=Path(__file__).resolve().parents[1];O=R/'art/studies/city-103'
a=Image.open(R/'art/studies/city-102/main.png').convert('RGB');b=Image.open(O/'main.png').convert('RGB')
for name,im in [('before',a),('after',b)]:
 im.crop((548,268,951,483)).resize((1209,645),Image.Resampling.LANCZOS).save(O/(name+'-city.png'))
 im.convert('L').crop((548,268,951,483)).resize((1209,645),Image.Resampling.LANCZOS).save(O/(name+'-gray.png'))
d=np.abs(np.asarray(a).astype(int)-np.asarray(b).astype(int));road=d[560:880,420:1000]
(O/'pixel-check.json').write_text(json.dumps({'locked_road_roi':[420,560,1000,880],'mean_absolute_rgb_change':float(road.mean()),'maximum_rgb_change':int(road.max())},indent=2))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>103 · Open distant street</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1440px;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}figure{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{margin:40px 0}button{padding:11px 16px;font:inherit;background:#36333d;color:white;border:1px solid #81716c;cursor:pointer;border-radius:5px}button.active{background:#89624c}figcaption{padding:8px 0;color:#c5bbc4}summary{cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>103 · Open distant street</h1><p>The single-story frontage row is removed. The rear brown tower has moved across the road onto the pale soil on the right, keeping its height and distance.</p><p><a href="#city">City closeup</a> · <a href="/art/studies/city-103/scene.blend">Editable scene</a></p><button id="old" onclick="show(false)">102 · Before</button> <button class="active" id="new" onclick="show(true)">103 · Cleaned-up street</button><p id="caption">103 · Cleaned-up street</p><a id="full-link" href="/art/studies/city-103/main.png"><img id="main" src="/art/studies/city-103/main.png"></a><section id="city"><h2>Same camera · placement comparison</h2><div class="grid"><figure><a href="/art/studies/city-103/before-city.png"><img src="/art/studies/city-103/before-city.png"></a><figcaption>Before</figcaption></figure><figure><a href="/art/studies/city-103/after-city.png"><img src="/art/studies/city-103/after-city.png"></a><figcaption>After · open frontage and brown tower on the right</figcaption></figure></div></section><details><summary>Grayscale comparison</summary><div class="grid"><img src="/art/studies/city-103/before-gray.png"><img src="/art/studies/city-103/after-gray.png"></div></details><script>function show(after){const p=after?'/art/studies/city-103/main.png':'/art/studies/city-102/main.png';document.getElementById('main').src=p;document.getElementById('full-link').href=p;document.getElementById('caption').textContent=after?'103 · Cleaned-up street':'102 · Before';document.getElementById('old').classList.toggle('active',!after);document.getElementById('new').classList.toggle('active',after);}</script></html>'''
(R/'prototype/review-103.html').write_text(s);(R/'prototype/index.html').write_text(s)
