from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/reviews/xenon-075'
def fig(p,t):return f'<figure><a href="{p}"><img loading="lazy" src="{p}" alt="{t}"></a><figcaption>{t}</figcaption></figure>'
a='/art/reviews/xenon-075/'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>075 · Ground, scrap and sky</title><style>body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.three{grid-template-columns:repeat(3,1fr)}figure{margin:0}img{width:100%;display:block}figcaption{padding:8px 0}p{max-width:1050px}button{background:#443a42;color:#fff;border:1px solid #807078;padding:9px;cursor:pointer}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid,.three{grid-template-columns:1fr}}</style><header><h1>075 · Ground, scrap and sky</h1><p>Approved alley buildings remain the baseline. This candidate combines dark lane dirt, lighter edge deposits, clustered stones, battered metal piles, slender distant buildings, and a clouded orange sky with a pale sun.</p><p><a href="#comparison">Before / after</a> · <a href="#ground">Ground</a> · <a href="#scrap">Scrap kit</a> · <a href="#sky">Sky options</a> · <a href="/art/reviews/xenon-075/scene.blend">Blender scene</a></p><button onclick="document.body.classList.toggle('gray')">Toggle grayscale</button></header>'''
s+='<section>'+fig(a+'render.png','075 · combined candidate')+'</section><section id="comparison"><div class="grid">'+fig('/art/reviews/xenon-074/render.png','074 · approved buildings / previous surroundings')+fig(a+'render.png','075 · new surroundings')+'</div></section>'
s+='<section id="ground"><h2>Ground and soil boundary</h2><div class="grid">'+fig(a+'reference-ground.png','Selected concept · soil, grit and quiet spaces')+fig(a+'ground.png','075 · two soils and embedded stones')+'</div></section>'
s+='<section id="scrap"><h2>Battered scrap</h2><div class="grid">'+fig(a+'near.png','Near-frame pile · hollow mouths, folds and rims')+fig('/art/studies/scrap-075/components.png','Editable components')+'</div></section>'
s+='<section id="sky"><h2>Sky density studies</h2><p>B is used in the combined candidate. The studies below compare cloud density; the combined render includes the final adjusted sun placement.</p><div class="grid three">'+''.join(fig('/art/studies/sky-075/'+v+'.png',v+' · '+t) for v,t in [('A','sparse'),('B','balanced'),('C','dense')])+'</div></section><section><p>Next review decisions: soil deposit width and contrast; foreground scrap density and round-mouth prominence; sky density. The distant city now uses slender architectural families with diminishing detail. The final remaining design choice is the <a href="/art/studies/landmark-076/index.html">coliseum-inspired landmark massing</a>. These are exploratory silhouettes, not finished architecture.</p></section></html>'
if (O/'render.png').exists():
 im=Image.open(O/'render.png');im.crop((0,790,1440,1080)).save(O/'near.png');im.crop((60,480,1380,920)).save(O/'ground.png')
 ref=Image.open(R/'art/reviews/xenon-001/selected-third.png');ref.crop((60,485,1380,915)).save(O/'reference-ground.png')
(R/'prototype/review-075.html').write_text(s);(R/'prototype/index.html').write_text(s)
