from pathlib import Path
from PIL import Image
import json,numpy as np
R=Path(__file__).resolve().parents[1];O=R/'art/studies/city-102';base=R/'art/studies/city-101/A/main.png'
a=Image.open(base).convert('RGB');b=Image.open(O/'main.png').convert('RGB')
for name,im in [('before',a),('after',b)]:
 im.crop((548,268,951,483)).resize((1209,645),Image.Resampling.LANCZOS).save(O/(name+'-city.png'))
 im.crop((886,274,939,469)).resize((318,1170),Image.Resampling.LANCZOS).save(O/(name+'-tower.png'))
 im.convert('L').crop((548,268,951,483)).resize((1209,645),Image.Resampling.LANCZOS).save(O/(name+'-gray.png'))
arr=np.abs(np.asarray(a).astype(int)-np.asarray(b).astype(int));road=arr[560:880,420:1000]
(O/'pixel-check.json').write_text(json.dumps({'locked_road_roi':[420,560,1000,880],'mean_absolute_rgb_change':float(road.mean()),'max_absolute_rgb_change':int(road.max()),'changed_pixels':int(np.any(road,axis=2).sum()),'full_scene_resolution':list(a.size)},indent=2))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>102 · Quiet distant façades</title><style>
body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1440px;padding:0 22px}h1{font-size:34px}a{color:#efbc91}img{width:100%;display:block}figure{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{margin:42px 0}button{padding:11px 16px;font:inherit;background:#36333d;color:#fff;border:1px solid #81716c;cursor:pointer;border-radius:5px}button.active{background:#89624c}figcaption{padding:8px 0;color:#c5bbc4}.source{max-height:680px;width:auto;max-width:100%;margin:auto}.wide{margin-top:14px}details{margin:30px 0}summary{cursor:pointer}.sub{color:#c5bbc4}@media(max-width:800px){.grid{grid-template-columns:1fr}}
</style><h1>102 · Quiet distant façades</h1><p>A’s original pixel-art layout is selected. The tiny window grids are replaced with mostly smooth walls, sparse worn paint and selective edge highlights.</p><p><a href="#city">City closeup</a> · <a href="#reference">Surface reference</a> · <a href="/art/studies/city-102/scene.blend">Editable scene</a></p>
<div><button id="old" onclick="show(false)">101 A · Before</button> <button id="new" class="active" onclick="show(true)">102 · Sparse painted details</button></div><p id="caption" class="sub">102 · Sparse painted details</p><a id="full-link" href="/art/studies/city-102/main.png"><img id="main" src="/art/studies/city-102/main.png"></a>
<section id="city"><h2>Same camera · façade detail</h2><div class="grid"><figure><a href="/art/studies/city-102/before-city.png"><img src="/art/studies/city-102/before-city.png"></a><figcaption>Before · repeated miniature windows</figcaption></figure><figure><a href="/art/studies/city-102/after-city.png"><img src="/art/studies/city-102/after-city.png"></a><figcaption>Now · quiet surfaces, unequal painted marks, restrained light catches</figcaption></figure></div></section>
<section id="reference"><h2>Painted surface direction</h2><div class="grid"><figure><img class="source" src="/references/user-city-study/smooth-facade-detail.png"><figcaption>Your reference · quiet violet face and selective warm accents</figcaption></figure><figure><img class="source" src="/art/studies/city-102/after-tower.png"><figcaption>Our tallest visible right tower · enlarged from the main render</figcaption></figure></div><p>The selected layout and building base colors remain intact. This pass changes the façade treatment; collapsed skyscraper geometry comes later.</p></section>
<details><summary>Grayscale comparison</summary><div class="grid wide"><figure><img src="/art/studies/city-102/before-gray.png"><figcaption>101 A</figcaption></figure><figure><img src="/art/studies/city-102/after-gray.png"><figcaption>102</figcaption></figure></div></details>
<script>function show(after){const p=after?'/art/studies/city-102/main.png':'/art/studies/city-101/A/main.png';document.querySelector('#main').src=p;document.querySelector('#full-link').href=p;document.querySelector('#caption').textContent=after?'102 · Sparse painted details':'101 A · Before';document.querySelector('#old').classList.toggle('active',!after);document.querySelector('#new').classList.toggle('active',after);}</script></html>'''
(R/'prototype/review-102.html').write_text(s);(R/'prototype/index.html').write_text(s)
