from pathlib import Path
from PIL import Image
import json,html
R=Path(__file__).resolve().parents[1];O=R/'art/studies/ground-085';A='/art/studies/ground-085/'
for rev,src in [('before',R/'art/studies/cloud-084/main.png'),('after',O/'main.png')]:
 im=Image.open(src);im.crop((455,680,650,745)).save(O/f'{rev}-interior.png');im.crop((238,654,648,875)).save(O/f'{rev}-body.png');im.crop((270,680,1120,878)).save(O/f'{rev}-breaks.png');im.convert('L').save(O/f'{rev}-gray.png')
Image.open(R/'references/user-soil-study/structural-road-grit.png').crop((20,95,155,165)).save(O/'reference-interior.png')
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{html.escape(label)}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>085 · Ground surface character</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.compare{position:relative}.compare img{width:100%}.compare .after{position:absolute;inset:0;clip-path:inset(0 0 0 50%)}input{width:100%;accent-color:#efbc91}small{color:#b5afa8}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>085 · Ground surface character</h1><p>The open road is the focus: clustered, low angular grit and shallow relief add texture between the breaks. Longitudinal structural cracks follow straight axes, with chipped boundaries and trapped fragments. Sky084 is locked at your 90/100 checkpoint.</p><p><a href="#body">Open soil</a> · <a href="#cracks">Breaks and reference</a> · <a href="/art/studies/ground-085/scene.blend">Editable Blender scene</a></p>'''
s+='<div class="compare"><img src="/art/studies/cloud-084/main.png" alt="084 baseline"><img class="after" id="after" src="'+A+'main.png" alt="085 candidate"></div><label for="slider">084 before ← drag comparison → 085 after</label><input id="slider" type="range" min="0" max="100" value="50" oninput="document.getElementById(\'after\').style.clipPath=\'inset(0 0 0 \'+this.value+\'%)\'"><p><a href="'+A+'main.png">Open full candidate</a></p>'
s+='<section id="body"><h2>Open-road surface at camera scale</h2><p>Crack-free interior crops:</p><div class="grid">'+fig(A+'before-interior.png','084 · open soil')+fig(A+'after-interior.png','085 · open soil')+'</div>'+fig(A+'reference-interior.png','US-02 · crack-free reference detail')+'<h3>Wider context</h3><div class="grid">'+fig(A+'before-body.png','084 · largely uniform open soil')+fig(A+'after-body.png','085 · clustered grains, low clods and fine relief')+'</div><p>The original fine pigment remains underneath. Surface variation comes from several grain sizes and uneven local groups, with actual sloped facets and a shallow bump treatment. This is a candidate, not a claimed 90–95 match.</p></section>'
s+='<details><summary>Surface measurements</summary><p>In sampled crack-free crops, detail contrast at a four-pixel radius changes from 2.22 (084) to 4.59 (085), compared with 4.98 in the supplied reference. These are descriptive texture statistics, not a fidelity score.</p><p><a href="'+A+'detail-statistics.json">Full measurements and crop coordinates</a></p></details>'
s+='<section id="cracks"><h2>Structural breaks and granular texture</h2><div class="grid">'+fig('/references/user-soil-study/structural-road-grit.png','US-02 · supplied reference: granular body and broken crack edges')+fig(A+'after-breaks.png','085 · native alley-camera crop')+'</div><p>Removed the broad sine drift from the longitudinal breaks. Shared deformation preserves the existing cut/lip junctions; trapped grains are placed onto the actual recessed surface.</p></section>'
if (O/'road-detail-native.png').exists():s+='<section><h2>Native closeup render</h2>'+fig(A+'road-detail-native.png','Same project camera · road crop rendered at twice the resolution')+'</section>'
s+='<section><h2>Original scene context</h2>'+fig('/private/captures/xenon-opening-cd.png','Purchased SQIV CD capture · local study reference')+'</section></html>'
(R/'prototype/review-085.html').write_text(s);(R/'prototype/index.html').write_text(s)
