from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-119'
for name,path in [('before',R/'art/studies/coliseum-116/main-4k.png'),('after',O/'main-4k.png')]:
    im=Image.open(path)
    im.crop((1400,350,2510,1140)).save(O/(name+'-detail.png'))
    im.crop((1800,420,2080,680)).save(O/(name+'-bay.png'))
    im.convert('L').resize((1440,1082)).save(O/(name+'-gray.png'))
    if name=='after':im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/'main.png')
style='body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1440px;margin:32px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:22px 0}figcaption{color:#c5bbc4}@media(max-width:800px){.pair{grid-template-columns:1fr}}'
s=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>119 · Visible masonry study</title><style>{style}</style><h1>119 · Visible masonry study</h1><p>The architectural detail and damage treatment is tested on a visible central bay. The surrounding scene and accepted coliseum placement remain fixed. This is a single-bay test before broader application.</p><p><a href="#detail">Before / after</a> · <a href="#reference">Reference</a> · <a href="/art/studies/coliseum-119/main-4k.png">4K render</a> · <a href="/art/studies/coliseum-119/scene.blend">Editable scene</a></p><img src="/art/studies/coliseum-119/main.png"><section id="detail"><h2>116 →119</h2><div class="pair"><figure><img src="/art/studies/coliseum-119/before-detail.png"><figcaption>116 baseline</figcaption></figure><figure><img src="/art/studies/coliseum-119/after-detail.png"><figcaption>119 central-bay study</figcaption></figure></div><h2>Central bay at equal enlargement</h2><div class="pair"><img src="/art/studies/coliseum-119/before-bay.png"><img src="/art/studies/coliseum-119/after-bay.png"></div></section><section id="reference"><h2>Reference detail</h2><img style="max-width:600px" src="/references/user-coliseum/upper-wall-detail.png"><p>UCL-02 user-supplied reference; original artwork by the project creator using ChatGPT Images 2.5. Geometry beyond reference resolution is inferred.</p></section><details><summary>Grayscale comparison</summary><div class="pair"><img src="/art/studies/coliseum-119/before-gray.png"><img src="/art/studies/coliseum-119/after-gray.png"></div></details><p>Development continues; no final acceptance or99 score is implied.</p></html>'
(R/'prototype/review-119.html').write_text(s)
