from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/characters-206';base='/art/studies/characters-206'
exports=json.loads((O/'pixel/exports.json').read_text())
rows=''
for n,h in [('traveler-a',49),('traveler-b',47)]:
 rows+=f'<article><h3>{n.title()}</h3><div class="variants">'
 for scale,c,label in [(1,24,'Reference-scale · 24 colors'),(1,16,'Reference-scale · 16 colors'),(2,24,'Double detail · 24 colors')]:
  tag=f'{n}-{h*scale}h-{c}c';x=next(x for x in exports if x['file']==tag+'.png')
  rows+=f'<figure><div class="checker spritebox"><img class="sprite" style="height:{x["logical_canvas"][1]*12//scale}px" src="{base}/pixel/{tag}-preview.png"></div><figcaption>{label}<br>{x["logical_body_width"]} × {h*scale} drawn grid · {x["logical_canvas"][0]} × {x["logical_canvas"][1]} canvas<br><a download href="{base}/pixel/{tag}.png">Logical-grid PNG</a> · <a download href="{base}/pixel/{tag}-preview.png">DOS-shape PNG</a></figcaption></figure>'
 rows+='</div></article>'
p='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>206 · Traveler-A & Traveler-B</title><style>
*{box-sizing:border-box}body{margin:0;background:#211f26;color:#f2e7dd;font:16px/1.5 system-ui}main{max-width:1700px;margin:auto;padding:26px}h1{font-size:34px;margin:0 0 8px}h2{margin-top:0}p{max-width:1000px;color:#cbbeb5}a{color:#f2bd8d}nav{position:sticky;top:0;background:#211f2bf0;z-index:5;display:flex;gap:12px;flex-wrap:wrap;padding:14px 0}button{font:inherit;background:#393440;color:#eee0d2;border:1px solid #756277;border-radius:5px;padding:8px 14px;cursor:pointer}button.active{background:#ad7150;color:#fff}section{padding:26px 0;border-top:1px solid #4a4148;scroll-margin-top:90px}.variants{display:flex;gap:18px;align-items:flex-end;flex-wrap:wrap}figure{margin:0;flex:1;min-width:180px;text-align:center}figcaption{font-size:14px;color:#cbbeb5;padding:12px}.checker{background-color:#5e5661;background-image:linear-gradient(45deg,#716974 25%,transparent 25%),linear-gradient(-45deg,#716974 25%,transparent 25%),linear-gradient(45deg,transparent 75%,#716974 75%),linear-gradient(-45deg,transparent 75%,#716974 75%);background-size:24px 24px;background-position:0 0,0 12px,12px -12px,-12px 0}.spritebox{height:642px;padding:15px;display:flex;align-items:flex-end;justify-content:center}.sprite{max-width:100%;object-fit:contain;image-rendering:pixelated}.animebox{height:780px;padding:22px}.animebox img{height:100%;max-width:100%;object-fit:contain}.scene{max-width:100%;width:100%;display:block}.controls{display:flex;gap:9px;flex-wrap:wrap;margin:14px 0}.refrow{display:flex;gap:24px;align-items:center}.refrow img{height:400px;image-rendering:pixelated}table{border-collapse:collapse}td,th{padding:10px 22px 10px 0;border-bottom:1px solid #4a4148;text-align:left}.note{font-size:14px;color:#beada1}.twocol{display:flex;gap:24px}.twocol>*{flex:1;min-width:0}article+article{margin-top:24px}details{padding:14px 0}@media(max-width:700px){main{padding:16px}.twocol{display:block}.spritebox{height:380px}.sprite{max-height:350px}.animebox{height:520px}.refrow{align-items:start}.refrow img{height:230px}}</style><main>
<h1>Traveler-A & Traveler-B</h1><p>Two rear-view character studies: a strict pixel treatment and scene-matched anime line art. Hair, clothing, and poses come from your photographs.</p>
<nav><a href="#scene">In the scene</a><a href="#pixel">Pixel sprites</a><a href="#anime">Anime study</a><a href="#reference">Reference analysis</a><a href="#files">Files</a></nav>
<section id="scene"><h2>Same scene, two treatments</h2><div class="controls"><button data-mode="pixel-native" class="active">Original-scale pixels</button><button data-mode="pixel-double">Double-detail pixels</button><button data-mode="anime">Anime · scene lighting</button></div><img id="sceneImage" class="scene" src="BASE/pixel-native-scene.png"><p id="sceneCaption">24 opaque colors per character, hard alpha, and nearest-neighbor scaling. The 1.2× tall DOS pixel shape preserves the intended proportions.</p><details open><summary>Character close-up</summary><img id="sceneDetail" class="scene" src="BASE/pixel-native-scene-detail.png" style="max-width:910px;margin-top:12px"></details><p class="note">Placement is a study: Traveler-A 1.72 m and Traveler-B 1.65 m, beside the former player anchor. These heights are assumptions for comparison.</p></section>
<section id="pixel"><h2>Pixel sprites</h2><p>The low-resolution pair matches the reference’s approximate silhouette height. The double-detail pair holds more of the shirt graphics and hair structure. Every downloadable sprite is an indexed PNG with one transparent index, no dithering, and no partially transparent pixels.</p>ROWS</section>
<section id="anime"><h2>Anime line art</h2><p>Muted indigo shadows, warm skin and cream fabrics, and dark ink contours. These are transparent illustrations; the scene test lights camera-facing cards with the scene’s actual lights. Flat cards share a single surface direction, so this is directional integration rather than full 3D character relighting. This first test does not add character contact shadows.</p><div class="twocol"><figure><div class="checker animebox"><img src="BASE/anime/traveler-a-anime.png"></div><figcaption>Traveler-A · <a download href="BASE/anime/traveler-a-anime.png">Transparent PNG</a></figcaption></figure><figure><div class="checker animebox"><img src="BASE/anime/traveler-b-anime.png"></div><figcaption>Traveler-B · <a download href="BASE/anime/traveler-b-anime.png">Transparent PNG</a></figcaption></figure></div><details><summary>How the lighting study works</summary><p>The illustration provides the clothing color and ink. Native transparent materials receive the saved scene lights and camera. Some shading is already drawn into the illustration. A future normal-map or shallow 3D character pass would make the hair, torso, and limbs respond in different directions and improve self-shadowing.</p><a href="BASE/anime/README.md">Lighting evidence and limitations</a></details></section>
<section id="reference"><h2>What the Xenon screenshot tells us</h2><div class="refrow"><img src="BASE/reference-analysis/rear-roger-dos-aspect-inspection.png"><div><table><tr><th>Measurement</th><th>Result</th></tr><tr><td>Drawn silhouette</td><td>17 × 49 logical pixels</td></tr><tr><td>DOS display correction</td><td>Pixel height = 1.2 × width</td></tr><tr><td>Equivalent square-pixel display</td><td>17 × 58.8 pixels</td></tr><tr><td>Original palette count</td><td>Not recoverable from this capture</td></tr><tr><td>Working palette for new sprites</td><td>24 colors + transparency; 16-color alternatives</td></tr></table><p>The file named xenon-opening-cd.png actually contains JPEG data. Scaling, compression, and color management create thousands of extra RGB values. A 20–24-color reconstruction approximates it well, but that is not proof of its original indexed palette.</p><p class="note">17 × 49 measures the visible figure in this screenshot, not the unseen resource canvas or any depth-scaling metadata. Reference crop is for private study; neither deliverable sprite contains Roger’s artwork.</p></div></div></section>
<section id="files"><h2>Saved assets</h2><p><a download href="BASE/character-sprites-206.zip">Download both character sets</a> · <a href="BASE/provenance.json">Source and generation record</a> · <a href="BASE/pixel/prompts.json">Pixel prompts</a> · <a href="BASE/pixel/exports.json">Exact dimensions and palettes</a></p><p class="note">Built-in image generation, followed by explicit pixel-grid/palette finishing for the pixel set. Original generated artwork is retained. The game-facing proportions interpret the high-angle photos rather than exactly tracing them. Static rear views only; animation and rigging are outside this study.</p></section>
<script>const base='BASE';const captions={'pixel-native':'24 opaque colors per character, hard alpha, and nearest-neighbor scaling. The 1.2× tall DOS pixel shape preserves the intended proportions.','pixel-double':'Twice the logical resolution, displayed at the same physical character size. More of the clothing motifs and hair structure survive.','anime':'Generated line-art cards rendered with the scene’s actual lights. This is a 2D lighting study; per-limb surface direction and self-shadowing require further normal or 3D work.'};document.querySelectorAll('button[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('button[data-mode]').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('sceneImage').src=base+'/'+(b.dataset.mode==='anime'?'anime/scene-composite.png':b.dataset.mode+'-scene.png');document.getElementById('sceneDetail').src=base+'/'+(b.dataset.mode==='anime'?'anime/scene-detail.png':b.dataset.mode+'-scene-detail.png');document.getElementById('sceneCaption').textContent=captions[b.dataset.mode]});</script></main></html>'''
p=p.replace('ROWS',rows).replace('BASE',base)
(R/'prototype/review-206.html').write_text(p)
