from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/scene-details-133';P='/art/studies/scene-details-133/'
regions={'clouds':(1280,0,2680,570),'transition':(1280,800,2700,1400),'alley':(0,670,920,1980),'joint':(1750,560,2190,970)}
for label,path in [('before',R/'art/studies/coliseum-132/selected/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/f'{label}-main.png')
 for name,box in regions.items():im.crop(box).save(O/f'{label}-{name}.png')
 im.resize((1440,1082),Image.Resampling.LANCZOS).convert('L').save(O/f'{label}-gray.png')
style='''*{box-sizing:border-box}body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:28px auto;padding:0 22px}a{color:#efbc91}img{display:block;width:100%}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:12px 0}figcaption{color:#c5bbc4;margin-top:7px}h1{font-size:32px}h2{font-size:25px;margin-top:44px}.controls{display:flex;flex-wrap:wrap;gap:12px;position:sticky;top:0;background:#19191eee;padding:10px 0;z-index:1}button{background:#30292d;border:1px solid #78616a;color:#eee7df;border-radius:5px;padding:10px 20px;font:inherit;cursor:pointer}button[aria-pressed=true]{background:#76534c;border-color:#bd8b79}details{margin:22px 0}summary{cursor:pointer}@media(max-width:750px){.pair{grid-template-columns:1fr}}'''
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>133 · Clouds, ruins and exposed services</title><style>{style}</style><h1>133 · Clouds, ruins and exposed services</h1><p>Finer cloud contours and layered color, ruined structures across the alley-to-city gap, and an exposed service opening with weathered steel and ledge. Includes the full-city 5× haze gradient and black arch crown joints.</p><p><a href="#clouds">Clouds</a> · <a href="#transition">Ruined buildings</a> · <a href="#alley">Exposed services and rust</a> · <a href="#joint">Black joints</a> · <a href="/prototype/review-132.html#street">Haze comparison</a></p><div class="controls"><button id="after" aria-pressed="true" onclick="choose('after')">Updated scene</button><button id="before" aria-pressed="false" onclick="choose('before')">Before these details</button></div><a href="{P}main-4k.png"><img id="main" src="{P}after-main.png"></a><p><a href="{P}main-4k.png">Open 4K render</a> · <a href="{P}scene.blend">Editable scene</a> · <a href="/art/studies/scene-details-133/prefabs.blend">Exposed-service prefab</a></p>'''
texts={'clouds':('Finer contours, softer layers','Cloud massing and the sky gradient stay in place. Small irregular edge breaks and connected subtle color layers replace the broad hard bands.'),'transition':('Broken buildings bridge the gap','Varied wall remnants, partial floors and collapsed slabs connect the alley to the first skyscrapers while keeping the street open.'),'alley':('Exposed services and weathered steel','One missing cladding panel opens into a real recessed cavity with conduits, cable loops and an enclosure. The left Y support and its ledge gain connected rust patches, pitting and runoff.'),'joint':('Black masonry joints','The shallow centered grooves now carry black ink from the arch crowns to the ledges above.')}
for key,(title,desc) in texts.items():
 h+=f'<section id="{key}"><h2>{title}</h2><p>{desc}</p><div class="pair"><figure><img loading="lazy" src="{P}before-{key}.png"><figcaption>Before</figcaption></figure><figure><img loading="lazy" src="{P}after-{key}.png"><figcaption>Updated</figcaption></figure></div></section>'
 if key=='clouds':h+='<details><summary>Reference close-up</summary><img loading="lazy" src="/art/studies/clouds-133/reference-cloud-detail.png"></details>'
 if key=='transition':h+='<details open><summary>Original reference: inspect the structural transition</summary><div class="pair"><img loading="lazy" src="/art/studies/city-transition-133/UCL01-transition-left.png"><img loading="lazy" src="/art/studies/city-transition-133/UCL01-transition-right.png"></div></details>'
 if key=='alley':h+='<details><summary>Original exposed-services and rust references</summary><div class="pair"><img loading="lazy" src="/art/studies/alley-damage-133/references/UCL01-left-exposed-services.png"><img loading="lazy" src="/art/studies/alley-damage-133/references/UCL01-right-rusted-support.png"></div></details>'
h+=f'''<details><summary>Full-scene grayscale comparison</summary><div class="pair"><img loading="lazy" src="{P}before-gray.png"><img loading="lazy" src="{P}after-gray.png"></div></details><p>Working scene for review. The new ruins and weathering remain adjustable; this is not a final lock.</p><p>UCL-01 is your original artwork, created with ChatGPT Images 2.5. All scene additions use editable native geometry/materials or the project’s own derived cloud assets.</p><script>function choose(v){{document.getElementById('main').src='{P}'+v+'-main.png';for(const x of ['before','after'])document.getElementById(x).setAttribute('aria-pressed',x===v)}}</script></html>'''
(R/'prototype/review-133.html').write_text(h)
