from pathlib import Path
from PIL import Image
import json,re,urllib.request
R=Path(__file__).resolve().parents[1];O=R/'art/studies/alley-rust-143';P='/art/studies/alley-rust-143/'
left=json.loads((R/'art/studies/alley-rust-137/crop.json').read_text())['bounds'];right=(2850,700,3770,2120)
for label,path in [('before',R/'art/studies/alley-rust-140/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/f'{label}-main.png')
 for name,box in [('left',left),('right',right)]:im.crop(box).save(O/f'{label}-{name}.png')
 im.resize((1440,1082)).convert('L').save(O/f'{label}-gray.png')
def pair(part):return f'<div class="pair"><figure><img src="{P}before-{part}.png"><figcaption>Before · 140</figcaption></figure><figure><img src="{P}after-{part}.png"><figcaption>Updated · 143</figcaption></figure></div>'
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>143 · A second oxide tone</title><style>body{{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:28px auto;padding:0 22px}}a{{color:#efbc91}}img{{width:100%;display:block}}.pair{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}figure{{margin:10px 0}}figcaption{{color:#c5bbc4}}button{{padding:12px;background:#433137;color:#fff;border:1px solid #957e77;cursor:pointer}}section{{margin:42px 0}}@media(max-width:700px){{.pair{{grid-template-columns:1fr}}}}</style><h1>143 · A second oxide tone</h1><p>A slightly lighter, warmer oxide layer adds smaller patches over the existing left-beam rust, with a modest preference for overlap.</p><button onclick="pick('after')">Updated</button> <button onclick="pick('before')">Before</button><img id="main" src="{P}after-main.png"><p><a href="{P}main-4k.png">Full 4K render</a> · <a href="{P}scene.blend">Editable scene</a></p><section id="left"><h2>Left support · two oxide tones</h2>{pair('left')}<p>Second-layer coverage: 4.9% in 4,096 area-weighted surface samples. About 40% of these new patches overlap the existing rust, compared with 24% for an unbiased placement. This includes hidden sides; visible coverage varies by face.</p></section><details><summary>Grayscale</summary>{pair('gray')}</details><p>Geometry and scene lighting preserved. Working candidate awaiting your review. The separate colosseum weathering study is not included.</p><script>function pick(v){{document.getElementById('main').src='{P}'+v+'-main.png'}}</script></html>'''
(R/'prototype/review-143.html').write_text(h);paths=re.findall(r'(?:src|href)="(/[^"#]+)"',h);missing=[p for p in paths if not(R/p.lstrip('/')).exists()];assert not missing,missing
(O/'delivery-check.json').write_text(json.dumps({'missing':missing,'resolution':list(Image.open(O/'main-4k.png').size),'http':urllib.request.urlopen('http://127.0.0.1:8765/prototype/review-143.html').status},indent=2));print('Published143')
