from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-126';p='/art/studies/coliseum-126/'
for name,path in [('before',R/'art/studies/coliseum-125/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path);im.crop((1300,320,2690,1230)).save(O/(name+'-detail.png'));im.crop((1650,660,2150,1190)).save(O/(name+'-bases.png'));im.convert('L').resize((1440,1082)).save(O/(name+'-gray.png'))
 if name=='after':im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/'main.png')
style='body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:32px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:22px 0}figcaption{color:#c5bbc4}@media(max-width:800px){.pair{grid-template-columns:1fr}}'
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>126 · Grouped arcades and pillar clearance</title><style>{style}</style><h1>126 · Grouped arcades and pillar clearance</h1><p>The expanded frontage organizes arches in groups of three, reserving space for the large pillars and their collars. Height and the established leaning curvature are retained.</p><p>Inset platforms are twice as tall. The upper two arcade levels now have visible column bases with one fewer ring than the ground level. An explicit outer arch contour helps the masonry joints read as part of the surround.</p><p><a href="#detail">Compare</a> · <a href="#bases">Platforms and bases</a> · <a href="{p}main-4k.png">4K image</a> · <a href="{p}scene.blend">Editable scene</a> · <a href="{p}kit.blend">Reusable kit</a></p><img src="{p}main.png"><section id="detail"><h2>125 →126</h2><div class="pair"><figure><img src="{p}before-detail.png"><figcaption>Previous uniform spacing</figcaption></figure><figure><img src="{p}after-detail.png"><figcaption>Three-arch groups and dedicated pillar space</figcaption></figure></div><a href="{p}after-detail.png">Open new detail at full size</a></section><section id="bases"><h2>Platforms and upper-level bases</h2><div class="pair"><img src="{p}before-bases.png"><img src="{p}after-bases.png"></div></section><details><summary>Grayscale comparison</summary><div class="pair"><img src="{p}before-gray.png"><img src="{p}after-gray.png"></div></details><p>The sky uses your Photoshop targets: #e35635 at the top, grading to #ec633f near the roofline and staying that orange below. Clouds use the muted strip palette. Locked surroundings are retained. Separate weathering and crown-fracture studies are still in development; this is not final centerpiece acceptance.</p></html>'''
(R/'prototype/review-126.html').write_text(h)
