from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/ground-086';A='/art/studies/ground-086/'
for name,src in [('before',R/'art/studies/ground-085/main.png'),('after',O/'main.png')]:Image.open(src).crop((210,590,1200,910)).save(O/f'{name}-road.png')
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>086 · Broad dirt deposits</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.compare{position:relative}.compare .after{position:absolute;inset:0;clip-path:inset(0 0 0 50%)}input{width:100%;accent-color:#efbc91}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>086 · Broad dirt deposits</h1><p>Sparse, shallow dirt mounds replace the dominant small-scale ripples. These are actual raised surfaces, roughly2–5 metres across and5–18cm high, with grains grounded on them. Fine soil pigment remains; quiet compacted areas separate the deposits.</p><p><a href="#road">Ground comparison</a> · <a href="#geometry">Untextured geometry proof</a> · <a href="/art/studies/ground-086/scene.blend">Editable Blender scene</a></p>'''
s+='<div class="compare"><img src="/art/studies/ground-085/main.png" alt="085 baseline"><img id="after" class="after" src="'+A+'main.png" alt="086 actual deposits"></div><label for="slider">085 before ← drag → 086 after</label><input id="slider" type="range" min="0" max="100" value="50" oninput="document.getElementById(\'after\').style.clipPath=\'inset(0 0 0 \'+this.value+\'%)\'"><p><a href="'+A+'main.png">Full candidate</a></p>'
s+='<section id="road"><h2>Ground at the game camera</h2><div class="grid">'+fig(A+'before-road.png','085 · repetitive small-scale relief')+fig(A+'after-road.png','086 · broad deposits and quieter intervals')+'</div></section>'
s+='<section id="geometry"><h2>Actual mound geometry</h2>'+fig(A+'clay-low-angle.png','Untextured low-angle view · true proportions, no height exaggeration')+'<p>The deposits rise above the existing road and locally cover portions of cracks. The crack axes remain unchanged. Small grains follow the new surface.</p></section>'
s+='<section><h2>Native road closeup</h2>'+fig(A+'road-detail.png','Same project camera, rendered at twice the resolution')+'</section>'
s=s.replace('roughly2–5','roughly 2–5').replace('and5–18cm','and 5–18 cm');s+='</html>'
(R/'prototype/review-086.html').write_text(s);(R/'prototype/index.html').write_text(s)
