from pathlib import Path
from PIL import Image
import json,re,urllib.request
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-148';P='/art/studies/coliseum-148/'
for label,path in [('before',R/'art/studies/alley-weathering-147/actual/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/f'{label}-main.png');im.crop((1400,350,2460,1240)).save(O/f'{label}-landmark.png');im.crop((1720,480,2120,850)).save(O/f'{label}-detail.png');im.crop((1680,710,1835,840)).save(O/f'{label}-cornice.png');im.resize((1440,1082)).convert('L').save(O/f'{label}-gray.png')
def pair(part):return f'<div class="pair"><figure><img src="{P}before-{part}.png"><figcaption>Before</figcaption></figure><figure><img src="{P}after-{part}.png"><figcaption>Updated</figcaption></figure></div>'
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>148 · Connected masonry wear</title><style>body{{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:28px auto;padding:0 22px}}a{{color:#efbc91}}img{{width:100%;display:block}}.pair{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}figure{{margin:10px 0}}figcaption{{color:#c5bbc4}}button{{padding:12px;background:#433137;color:#fff;border:1px solid #957e77;cursor:pointer}}section{{margin:42px 0}}@media(max-width:700px){{.pair{{grid-template-columns:1fr}}}}</style><h1>148 · Connected masonry wear</h1><p>Connected deposits follow the broken upper cornice into the wall and column shoulder. A separate stepped loss interrupts three stone courses beside a tower.</p><button onclick="pick('after')">Updated</button> <button onclick="pick('before')">Before</button><img id="main" src="{P}after-main.png"><p><a href="{P}main-4k.png">Full 4K render</a> · <a href="{P}scene.blend">Editable scene</a> · <a href="{P}kit.blend">Colosseum kit</a></p><section id="detail"><h2>Upper arcade</h2>{pair('detail')}</section><section id="cornice"><h2>Stepped cornice loss</h2>{pair('cornice')}</section><section><h2>Whole landmark</h2>{pair('landmark')}</section><section><h2>Original reference</h2><img src="/art/studies/coliseum-134/analysis/independent/reference-display.png"><p>Your original artwork, created with ChatGPT Images 2.5.</p></section><details><summary>Grayscale</summary>{pair('gray')}</details><p id="status">Working candidate; user approval remains pending.</p><script>function pick(v){{document.getElementById('main').src='{P}'+v+'-main.png'}}</script></html>'''
if (O/'critic.json').exists():
 d=json.loads((O/'critic.json').read_text());sc=d.get('scores',{});h=h.replace('<p id="status">','<p>Independent scores: '+', '.join(k.replace('_',' ')+': '+str(v) for k,v in sc.items())+'.</p><p id="status">')
(R/'prototype/review-148.html').write_text(h);paths=re.findall(r'(?:src|href)="(/[^"#]+)"',h);missing=[p for p in paths if not(R/p.lstrip('/')).exists()];assert not missing,missing;(O/'delivery-check.json').write_text(json.dumps({'missing':missing,'resolution':list(Image.open(O/'main-4k.png').size),'http':urllib.request.urlopen('http://127.0.0.1:8765/prototype/review-148.html').status},indent=2));print('Published148')
