"""Standalone review for the first visible distributed colosseum crumbling pass."""
from pathlib import Path
import json,urllib.request
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-190';P=R/'prototype/review-190.html'
P.write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>190 · Colosseum crumbling</title>
<style>
:root{color-scheme:dark;--bg:#1b1920;--panel:#25212a;--ink:#eee6df;--muted:#b8aab0;--accent:#df9472}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,sans-serif}main{max-width:1160px;margin:auto;padding:42px 24px 70px}h1{font-size:34px;font-weight:640;line-height:1.15;margin:8px 0 16px}h2{font-size:22px;margin:0 0 12px}.eyebrow{color:var(--accent);font-size:13px;letter-spacing:.10em;text-transform:uppercase}p{max-width:850px;color:var(--muted);margin:10px 0}a{color:#efb797}button{font:inherit;border:1px solid #64515b;border-radius:7px;background:#312934;color:var(--ink);padding:9px 18px;cursor:pointer}button[aria-pressed=true]{background:#d99a7d;color:#211b21;border-color:#d99a7d}.toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:22px 0 12px}.toolbar span{color:var(--muted);font-size:14px;margin-left:auto}.frame{background:#100e13;border:1px solid #493d46;border-radius:9px;overflow:hidden;text-align:center}.frame img{display:block;width:100%;height:auto;max-width:1000px;margin:auto}.frame a{display:block}figure{margin:0}figcaption{font-size:13px;color:var(--muted);padding:12px 16px}.note{font-size:13px;max-width:none}.section{margin-top:44px}.refs{display:grid;grid-template-columns:1.6fr 1fr 1fr;gap:16px}.refs figure{background:var(--panel);border:1px solid #493d46;border-radius:8px;overflow:hidden}.refs img{display:block;width:100%;height:300px;object-fit:contain;background:#161218}.download{display:inline-block;text-decoration:none;border:1px solid #775846;border-radius:7px;padding:10px 16px;margin-top:12px}details{margin-top:30px;padding:16px;background:var(--panel);border:1px solid #493d46;border-radius:8px}summary{cursor:pointer;color:#e4c3b0}.history{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.history img{width:100%;display:block}.status{display:inline-block;font-size:13px;padding:4px 9px;border-radius:5px;background:#3b2e2c;color:#edb298;margin-top:8px}footer{font-size:13px;color:var(--muted);margin-top:36px}@media(max-width:700px){main{padding:26px 14px}h1{font-size:28px}.refs,.history{grid-template-columns:1fr}.toolbar span{width:100%;margin:0}.refs img{height:280px}}
</style><main>
<div class="eyebrow">Study 190 · First broader weathering pass</div><h1>Colosseum wall crumbling</h1>
<p>Thirty connected damage groups across the three arcade levels and upper walls. Larger jagged recesses and exposed masonry interrupt the clean wall faces while keeping the arches and structural outlines intact.</p>
<p>This is a standalone colosseum preview. The latest alley rust work is shown separately.</p><div class="status">First pass for review · no final score or user approval</div>
<section id="comparison" aria-label="Before and after comparison"><div class="toolbar"><button id="after" aria-pressed="true">With crumbling</button><button id="before" aria-pressed="false">Before</button><span>Switch views to compare the whole landmark</span></div>
<figure class="frame"><a id="full" href="../art/studies/coliseum-190/landmark-v2-painted.png" target="_blank"><img id="main" src="../art/studies/coliseum-190/landmark-v2-painted.png" alt="Colosseum with distributed wall crumbling"></a><figcaption id="caption">Current pass: connected losses on visible wall faces, with quieter stretches between.</figcaption></figure>
<p class="note">The before image is resized from the previous full-resolution render; fine outline softness differs slightly. Compare the damage shapes and distribution.</p></section>
<section class="section" id="detail"><h2>Closer view</h2><figure class="frame"><a href="../art/studies/coliseum-190/detail-v2.png" target="_blank"><img src="../art/studies/coliseum-190/detail-v2.png" alt="Enlarged view of connected crumbling around upper walls and arcade shoulders"></a><figcaption>Upper-wall losses are strongest; the lower arcade damage is softened by the existing haze and foreground buildings.</figcaption></figure></section>
<section class="section" id="references"><h2>Reference shapes and frequency</h2><p>Look for irregular dark masonry loss at openings, arch shoulders and wall joints, with smaller fragments around the larger groups.</p><div class="refs">
<figure><a href="../art/studies/coliseum-190/reference/UCL01-landmark.png" target="_blank"><img src="../art/studies/coliseum-190/reference/UCL01-landmark.png" alt="Original colosseum reference enlarged"></a><figcaption>UCL-01 · Your original artwork, created with ChatGPT Images 2.5.</figcaption></figure>
<figure><a href="../art/studies/coliseum-190/reference/UCL02-upperwall.png" target="_blank"><img src="../art/studies/coliseum-190/reference/UCL02-upperwall.png" alt="Upper wall damage reference detail"></a><figcaption>UCL-02 · Detail of your original artwork: clustered exposed masonry around openings.</figcaption></figure>
<figure><a href="../art/studies/coliseum-190/reference/DP03-full.png" target="_blank"><img src="../art/studies/coliseum-190/reference/DP03-full.png" alt="Industrial structure reference by Darius Puia"></a><figcaption>DP-03 · Darius Puia / BakaArts. Secondary reference for selective wear and intact structural spans. <a href="https://theinspirationgrid.com/imaginative-sci-fi-illustrations-by-darius-puia/" target="_blank">Source</a>.</figcaption></figure>
</div></section>
<section class="section" id="native"><h2>Editable native study</h2><p>The recesses are modeled into the wall faces. Original wall vertices, architectural boundaries and untouched faces are preserved.</p><a class="download" href="../art/studies/coliseum-190/candidate-v2.blend" download="colosseum-crumbling-190-v2.blend">Download Blender study</a> <a class="download" href="../art/studies/coliseum-190/payload-v2.blend" download="colosseum-crumbling-190-v2-meshes.blend">Download changed meshes</a></section>
<details id="history"><summary>Earlier small-pocket study — held</summary><p>The first version placed too many small recesses behind structural detail. It did not create enough visible change, so it was held rather than integrated. Its source, proof and review remain archived.</p><div class="history"><figure><img src="../art/studies/coliseum-190/held-v1/landmark-painted.png" alt="Earlier held small-pocket crumbling study"><figcaption>Held first attempt</figcaption></figure><figure><img src="../art/studies/coliseum-190/landmark-v2-painted.png" alt="Current larger connected crumbling study"><figcaption>Current larger connected groups</figcaption></figure></div></details>
<footer>Native geometry and materials. Standalone study pending review; no projected reference artwork.</footer>
</main><script>
const base='../art/studies/coliseum-190/';const image=document.getElementById('main'),full=document.getElementById('full'),caption=document.getElementById('caption');for(const key of ['before','after'])document.getElementById(key).addEventListener('click',()=>{const after=key==='after';image.src=base+(after?'landmark-v2-painted.png':'baseline-landmark.png');full.href=image.src;image.alt=after?'Colosseum with distributed wall crumbling':'Colosseum before this crumbling pass';caption.textContent=after?'Current pass: connected losses on visible wall faces, with quieter stretches between.':'Previous retained colosseum before the distributed wall crumbling pass.';for(const id of ['before','after'])document.getElementById(id).setAttribute('aria-pressed',String(id===key));});
</script></html>''')
paths=['/prototype/review-190.html','/art/studies/coliseum-190/landmark-v2-painted.png','/art/studies/coliseum-190/baseline-landmark.png','/art/studies/coliseum-190/detail-v2.png','/art/studies/coliseum-190/reference/UCL01-landmark.png','/art/studies/coliseum-190/reference/UCL02-upperwall.png','/art/studies/coliseum-190/reference/DP03-full.png','/art/studies/coliseum-190/payload-v2.blend']
checks=[]
for p in paths:
 req=urllib.request.Request('http://127.0.0.1:8765'+p,method='HEAD')
 with urllib.request.urlopen(req)as response:checks.append({'path':p,'status':response.status,'bytes':response.headers.get('Content-Length')})
(O/'delivery-check-v2.json').write_text(json.dumps({'page':'http://127.0.0.1:8765/prototype/review-190.html','checks':checks,'user_approved':False},indent=2));print(json.dumps(checks))
