from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/ground-087';A='/art/studies/ground-087/'
for v in 'ABC':Image.open(O/f'{v}-main.png').crop((210,590,1200,910)).save(O/f'{v}-road.png')
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>087 · Continuous uneven ground</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}button{font:inherit;background:#34313b;color:#eee;padding:12px 24px;border:1px solid #9b887b;cursor:pointer}button.active{background:#785440}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>087 · Continuous uneven ground</h1><p>The same tall mounds now sit within a continuous ground surface. Broader, lower rises fill the intervals, with roughly 20% of the sampled road kept flat. Smooth transitions replace separate mound overlays; existing cracks and grains follow the terrain.</p><p>A: broad rises up to 6 cm · B: up to 7.5 cm · C: up to 9 cm. Tall mounds stay at about 18 cm in all three. Broad rise radii range from 3.2–5.2 m.</p><div><button onclick="pick('A',this)">A · gentler</button><button class="active" onclick="pick('B',this)">B · middle</button><button onclick="pick('C',this)">C · stronger</button></div>'''
s+=f'<section><a id="full-link" href="{A}B-main.png"><img id="full" src="{A}B-main.png" alt="B full scene"></a></section><section id="body"><h2>Same ground crop</h2><img id="crop" src="{A}B-road.png" alt="Selected ground crop"></section>'
s+='<section><h2>All three at camera scale</h2>'
for v in 'ABC':s+=fig(A+v+'-road.png',v)
s+='</section><section><h2>Untextured terrain proof</h2>'+fig(A+'B-clay.png','B · low-angle view, true heights without exaggeration')+'</section><section><h2>Previous isolated mounds</h2>'+fig('/art/studies/ground-086/after-road.png','086 baseline')+'</section><p>'+' · '.join(f'<a href="{A}{v}-scene.blend">{v} Blender scene</a>' for v in 'ABC')+'</p>'
s+='''<script>function pick(v,b){document.querySelectorAll('button').forEach(e=>e.classList.remove('active'));b.classList.add('active');document.getElementById('full').src='/art/studies/ground-087/'+v+'-main.png';document.getElementById('full-link').href=document.getElementById('full').src;document.getElementById('crop').src='/art/studies/ground-087/'+v+'-road.png';}</script></html>'''
(R/'prototype/review-087.html').write_text(s);(R/'prototype/index.html').write_text(s)
