from pathlib import Path
from PIL import Image
import json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');O=R/'art/reviews/xenon-058';P=R/'prototype'
for stage in ['055','057','058']:
 im=Image.open(R/f'art/reviews/xenon-{stage}/render.png')
 im.crop((1050,30,1440,550)).save(O/f'{stage}-facade.png')
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}p{max-width:960px;color:#c9c1c9}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.trio{grid-template-columns:repeat(3,1fr)}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}button{padding:10px;background:#38313e;color:white;border:1px solid #79637a}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
a='/art/reviews/xenon-058/'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>058 · Sparse architectural color wear</title><style>{css}</style><header><h1>058 · Sparse architectural color wear</h1><p>The blanket wall mottling from 057 is removed. Its replacement uses larger, sparse color patches with an edge preference. Pipe and small rectangular duct materials retain 057.</p><p><a href="#facade">Facade comparison</a> · <a href="#detail">Native detail</a> · <a href="{a}scene.blend">Editable Blender scene</a></p><button onclick="document.body.classList.toggle(\'gray\')">Toggle grayscale</button></header><section><h2>Camera scale first</h2><div class="grid">'+fig('/art/reviews/xenon-057/render.png','057 · Rejected wall mottling')+fig(a+'render.png','058 · Sparse palette variation; retained services')+'</div></section><section id="facade"><h2>Wall progression</h2><div class="grid trio">'+''.join(fig(a+v+'-facade.png',t) for v,t in [('055','055 · Earlier wall treatment'),('057','057 · Too uniformly mottled'),('058','058 · Quieter interiors')])+'</div></section><section id="detail"><h2>Native high-resolution facade</h2><div class="grid">'+fig('/art/reviews/xenon-057/facade-detail.png','057 · Before')+fig(a+'facade-detail.png','058 · After')+'</div><p>The new layer mixes related violet-gray, muted gray, reddish brown and warm clay tones. Broad world-space clusters avoid restarting the same pattern on each panel. A component-boundary mask favors edges and corners; it is a bounding-shape approximation, not a curvature or water-flow simulation. Existing cracks, coating loss and runoff remain separate.</p></section><section><h2>Reference direction</h2><div class="grid">'+fig('/art/reviews/xenon-051/reference-facade.png','Selected concept · quiet fields and localized detail')+fig('/references/user-pipe-surface-study/pipe-detail-fine-geometry-and-weathering.png','UP-03 · material study')+'</div><p>References: UP-01, UP-03, DP-08. All candidate images are native Blender renders. Scene layout and camera are preserved. This pass awaits user review.</p></section></html>'
(P/'review-058.html').write_text(page);(P/'index.html').write_text(page)
