from pathlib import Path
from PIL import Image
import json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');O=R/'art/reviews/xenon-051';P=R/'prototype'
for n,box in [('facade',(1050,30,1440,550)),('pipes',(280,120,560,670))]:Image.open(O/'render.png').crop(box).save(O/(n+'.png'))
if not (P/'review-050.html').exists():(P/'review-050.html').write_text((P/'index.html').read_text())
css='''*{box-sizing:border-box}body{margin:0;background:#19181e;color:#eee7df;font:16px system-ui}header,section{padding:24px 3vw}h1{font-size:30px}p{max-width:1000px;line-height:1.6;color:#c9c1c9}a{color:#efbc91}button{padding:10px 16px;background:#38313e;color:#eee;border:1px solid #79637a;border-radius:6px;cursor:pointer}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.trio{grid-template-columns:1fr 1fr 1fr}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid{grid-template-columns:1fr}}'''
def fig(path,cap):return f'<figure><a href="{path}" target="_blank"><img src="{path}" alt="{cap}"></a><figcaption>{cap}</figcaption></figure>'
def local(name,cap):return fig('../art/reviews/xenon-051/'+name+'.png',cap)
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grit, scars and shadow · 051</title><style>{css}</style><header><h1>Grit, scars and shadow · 051</h1><p>C hybrid, with finer clustered surface wear. Facades gain pinprick chips, small scars and sparse pale fragments. Services use a separate, quieter enamel-wear treatment. Darker undersides group platform shadows; fine crease lines recede beneath stronger contours.</p><p><a href="#facade">Facade closeups</a> · <a href="#pipes">Pipe closeups</a> · <a href="#alley">Whole alley</a> · <a href="../art/reviews/xenon-051/scene.blend">Blender scene</a> · <a href="review-050.html">050 style study</a></p><button onclick="document.body.classList.toggle('gray')">Toggle grayscale</button></header>'''
for region in ['facade','pipes']:
 page+=f'<section id="{region}"><h2>{region.title()} · reference / 050 / 051</h2><div class="grid trio">'+local('reference-'+region,'Selected concept · detail direction')+local('baseline-'+region,'050 · approved hybrid direction')+local(region,'051 · small wear and grouped shadows')+'</div></section>'
page+='<section id="alley"><h2>Whole-alley comparison</h2><div class="grid">'+fig('../art/reviews/xenon-050/hybrid.png','050 · C hybrid')+local('render','051 · finer surface vocabulary')+'</div><p>Camera, geometry, broad warm/cool coating, existing cracks and runoff remain fixed. These are native procedural material details, with no image projection or paintover. Fine wear is region-gated, rather than a uniform surface-wide noise layer. The smaller marks are color details rather than glossy bumps. Next refinement: make more of the small scars respond to seams and fasteners; the current placement follows broad weathering regions.</p></section>'
page+='<section><h2>Published reference · Darius Puia / BakaArts</h2>'+fig('../references/darius-puia/DP-08-layered-infrastructure.jpg','DP-08 · layered infrastructure — reference only')+'<p>Compare quiet surface areas with small, clustered chips. <a href="https://theinspirationgrid.com/imaginative-sci-fi-illustrations-by-darius-puia/">Source and artist credit</a>. Additional direction: HM-03 and AF-06, credited in the preceding style study.</p></section></html>'
(P/'index.html').write_text(page);(P/'review-051.html').write_text(page)
