from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/ground-089';A='/art/studies/ground-089/'
for label,p in [('before',R/'art/studies/ground-088/main.png'),('after',O/'main.png')]:Image.open(p).crop((210,590,1200,910)).save(O/f'{label}-road.png')
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>089 · Integrated packed soil</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.compare{position:relative}.compare .after{position:absolute;inset:0;clip-path:inset(0 0 0 50%)}input{width:100%;accent-color:#efbc91}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>089 · Packed soil in the alley</h1><p>The approved 088 soil relief is integrated into the road surface. C’s broad shape and A’s mean height are retained. The separate road rock layer stays hidden while the terrain is reviewed.</p><p><a href="#body">Ground comparison</a> · <a href="#geometry">Untextured proof</a> · <a href="/art/studies/ground-089/scene.blend">Editable Blender scene</a></p>'''
s+='<div class="compare"><img src="/art/studies/ground-088/main.png" alt="088 macro terrain"><img class="after" id="after" src="'+A+'main.png" alt="089 integrated soil"></div><label for="slider">088 before ← drag → 089 integrated</label><input id="slider" type="range" min="0" max="100" value="50" oninput="document.getElementById(\'after\').style.clipPath=\'inset(0 0 0 \'+this.value+\'%)\'">'
s+='<section id="body"><h2>At the main camera</h2><div class="grid">'+fig(A+'before-road.png','088 · macro terrain')+fig(A+'after-road.png','089 · integrated relief')+'</div></section>'
s+='<section><h2>Native detail render</h2>'+fig(A+'road-detail.png','Same project camera, twice the resolution')+'</section>'
s+='<section id="geometry"><h2>Untextured integrated surface</h2>'+fig(A+'clay.png','Same low-angle proof camera · native geometry')+'</section></html>'
(R/'prototype/review-089.html').write_text(s);(R/'prototype/index.html').write_text(s)
