from pathlib import Path
from PIL import Image
import json,re,urllib.request
R=Path(__file__).resolve().parents[1];O=R/'art/studies/alley-weathering-145';P='/art/studies/alley-weathering-145/'
for src in ['combined/combined-4k.png','combined/before-4k.png']:
 p=O/src;im=Image.open(p).convert('RGB');im.resize((1800,round(im.height*1800/im.width)),Image.Resampling.LANCZOS).save(p.with_name(p.stem+'-display.png'));im.convert('L').save(p.with_name(p.stem+'-gray.png'))
actual=(O/'actual/main-4k.png').exists()
if actual:
 plan=json.loads((O/'actual/placement-audit.json').read_text());box=plan.get('crop_bounds',[240,0,750,1200]);box=tuple(int(v)for v in box)
 for key,src in [('before',R/'art/studies/alley-rust-143/main-4k.png'),('after',O/'actual/main-4k.png')]:
  im=Image.open(src).convert('RGB');im.resize((1800,round(im.height*1800/im.width)),Image.Resampling.LANCZOS).save(O/f'actual/{key}-display.png');im.crop(box).save(O/f'actual/{key}-crop.png');im.convert('L').crop(box).save(O/f'actual/{key}-gray.png')
actual_section=f'''<section id="alley"><h2>At the alley camera</h2><div class="pair"><figure><img src="{P}actual/before-crop.png"><figcaption>Before</figcaption></figure><figure><img src="{P}actual/after-crop.png"><figcaption>Weathering pilot</figcaption></figure></div><details><summary>Full scene</summary><img src="{P}actual/after-display.png"></details><p><a href="{P}actual/main-4k.png">Full 4K render</a> · <a href="{P}actual/scene.blend">Editable scene candidate</a></p></section>'''if actual else ''
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>145 · Alley weathering</title><style>body{{background:#191a20;color:#eee6dd;font:17px/1.55 system-ui;max-width:1600px;margin:30px auto;padding:0 24px}}h1,h2{{font-weight:600}}p{{max-width:950px}}a{{color:#edbb98}}nav{{display:flex;gap:18px;flex-wrap:wrap;margin:16px 0 28px}}img{{display:block;width:100%;height:auto}}figure{{margin:12px 0}}figcaption{{color:#c2b7b1;font-size:15px}}.pair{{display:grid;grid-template-columns:1fr 1fr;gap:24px}}.three{{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}}button{{background:#443c42;color:#fff;border:1px solid #80716d;border-radius:5px;padding:10px 18px;font:inherit;cursor:pointer}}section{{margin:50px 0}}details{{margin:22px 0}}summary{{cursor:pointer}}@media(max-width:760px){{.pair,.three{{grid-template-columns:1fr}}}}</style>
<h1>145 · Alley weathering</h1><p>Broad warm light across cool panels, a few meaningful breaks, and weathering tied to edges and hardware. The rust now includes broader runs that narrow into uneven, broken tails.</p><nav><a href="#streaks">Panel study</a><a href="#lighting">Light response</a><a href="#damage">Depth</a>{'<a href="#alley">Alley placement</a>'if actual else ''}<a href="#reference">Reference</a></nav>
<section id="streaks"><button onclick="show('combined-4k')">Weathered</button> <button onclick="show('before-4k')">Clean control</button><img id="hero" src="{P}combined/combined-4k-display.png"><p>Selective bolts carry compact dark oxide stains. Fine trails alternate with a few broader, tapering runs. The large top loss, two shallow pits, deeper impact hole and dark crack use actual recessed geometry.</p><p><a href="{P}combined/combined-4k.png">Full 4K component render</a> · <a href="{P}combined/panel-kit.blend">Editable panel kit</a></p></section>
{actual_section}
<section id="lighting"><h2>The same material under different light</h2><p>The broad coating pattern stays attached to the panels; its warm response changes with the light. Cool fill alone removes the warm highlight.</p><div class="three"><figure><img src="{P}material/key-left.png"><figcaption>Warm key from the left</figcaption></figure><figure><img src="{P}material/key-right.png"><figcaption>Warm key moved right</figcaption></figure><figure><img src="{P}material/cool-fill-only.png"><figcaption>Cool fill only</figcaption></figure></div></section>
<section id="damage"><h2>Physical depth</h2><img src="{P}combined/clay.png"><details><summary>Grayscale readability</summary><img src="{P}combined/combined-4k-gray.png"></details></section>
<section id="reference"><h2>Reference</h2><img src="{P}geometry/user-detail-reference.png"><p>Original project artwork by the project creator, made using ChatGPT Images 2.5. This closeup guides surface hierarchy and damage; it is not projected onto the model.</p></section><p>This is a component and placement study toward the 95/100 target. It is not a finished weathering rollout or an approval claim.</p><script>function show(n){{document.getElementById('hero').src='{P}combined/'+n+'-display.png'}}</script></html>'''
p=R/'prototype/review-145.html';p.write_text(h);links=re.findall(r'(?:src|href)="(/[^"#]+)"',h);missing=[q for q in links if not(R/q.lstrip('/')).exists()];assert not missing,missing
(O/'publication-check.json').write_text(json.dumps({'missing':missing,'http':urllib.request.urlopen('http://127.0.0.1:8765/prototype/review-145.html').status,'actual_scene_included':actual},indent=2));print('Published145')
