import json
from pathlib import Path
R=Path('/PATH/TO/transmissions-from-alpha-centauri');O=R/'art/reviews/xenon-068'
rows=[
('L1-upper-shell','Left upper shell and parapet','Several vertical/diagonal splits descend from top edges or panel seams. Isolated chips and coating loss are more frequent than complete fractures.','brittle_panel','30–45%','1 principal path, 0–2 branches','0.45–0.95','2–6','3–15','1–3','Prefer top-edge entry; stop at panel seams. Do not mistake flaked paint islands for holes.'),
('L2-sloped-bays','Left sloped bays, jambs, and recessed-panel surrounds','Corner-origin splits cross the sloping strips; a few larger edge breaks interrupt otherwise clean planes.','opening_surround','45–65%','1 principal path, 1–2 branches','0.55–1.0','3–9','5–25','1–3','Start at opening corners or changes of slope. Continue around a chamfer only when the two faces belong to the same solid.'),
('L3-lower-panels','Left ground-level infill and narrow piers','One warm panel has a strong diagonal from its bottom edge toward the opposite upper corner. Adjacent blue piers show branching vertical splits and enlarged edge losses.','panel_and_pier','60–80%','1–2 principal paths, 1–3 branches','0.7–1.0','4–12','8–35','2–4','Separate broad-panel diagonal preset from slender-pier vertical preset. Keep some neighboring panels intact.'),
('L4-service-recess','Left service-bay backing and low plinths','Backing panels have sparse seam-linked cracks; the low projecting block is more broken along its perimeter. Pipes themselves retain continuous skins.','plinth_and_backing','25–45%','0–1 principal path, 0–2 branches','0.35–0.85','3–8','5–25','1–3','Concentrate damage at block corners and base contact. Exclude service housings until material is classified.'),
('R1-front-column','Right foreground warm columns, jambs, and base walls','Long irregular vertical/oblique routes cross the column faces. Branches reach side edges; cracks flare at the base and intersections.','hero_pier','65–85%','1–2 principal paths, 2–4 branches','0.75–1.0','5–14','10–40','2–5','Use a connected sparse network, not many parallel scratches. Coordinate paths across a column chamfer.'),
('R2-window-kicks','Right window kick panels, mullion surrounds, and long spandrels','Fine diagonals traverse the broad strips below windows. Corners and seams anchor breaks; a few larger vertical fractures pass beside openings.','window_surround','35–55%','1 principal path, 0–2 branches','0.5–1.0','2–7','3–18','1–3','Keep glazing separate. Never continue a concrete cutter through glass or a metal slider frame.'),
('R3-mid-wall','Right middle/rear wall panels and service-opening surrounds','The clearest connected networks: a few long diagonals intersect and branch, reaching panel boundaries and missing edge fragments. Nearby bays vary substantially in density.','connected_panel','50–70%','1–2 principal paths, 2–4 branches','0.65–1.0','3–10','6–30','2–4','Place one hero network in a cluster of two or three damaged bays, then leave a quieter bay. Panel boundaries interrupt paths.'),
('R4-buttresses','Right sloped concrete supports and their bearing zones','The diagonal supports have large calm centers. Most obvious damage is at the feet, side edges, and upper contacts; fine transverse splits are secondary.','bearing_support','40–65%','0–1 principal path, 0–2 branches','0.3–0.8','3–10','8–35','2–4','Bias seeds toward end thirds and contact zones. Do not cover every support with the current six-route showcase network.'),
('S-platforms','Walkway fascia, projecting ledges, and Y supports','Long fascia edges have chips and occasional interruptions. The steel Y beams show wear along edges and joins; concrete-like branching is not clearly supported.','ledge_or_metal','20–35% of mineral fascias','0–1 short path, 0–1 branch','0.2–0.6','2–6','3–12','1–2','Apply fractures only to confirmed brittle fascia pieces. Steel Y members get coating loss, rust, and rare dents; no concrete cuts.'),
('G-paving','Street surface','Large irregular polygons and long connected fissures cross the street, with grit along seams. These are much wider-spaced than facade networks.','pavement','Separate continuous network','Low-valence network; avoid regular cells','Not per-panel','8–30','5–25','Separate erosion','Use 1.5–4 m cell spacing as an initial scene-scale guess; keep traversable surface/collision intact. Dedicated ground pass after architecture.')]
items=[]
for row in rows:
 id,title,evidence,family,occupancy,paths,span,width,depth,flare,notes=row
 items.append(dict(id=id,title=title,observed=evidence,preset=family,estimated_damaged_component_fraction=occupancy,paths=paths,path_span_fraction=span,estimated_mouth_width_mm=width,estimated_depth_mm=depth,edge_flare_multiplier=flare,placement=notes))
a={'status':'planning estimates, not measured material dimensions','final_material':{'mouth_darkening':.45,'deepest_darkening':1.0,'weathering':'project original host finish into recess','specular':'retain narrow physical mouth-only reflection'},'regions':items,'global_rules':{'topology':'Main routes connect two edges, an opening corner, an existing fracture, or a spall. Only short secondary hairlines may taper inside a face.','variation':'Choose building damage zone, then component eligibility, then connected paths, then local fracture shape. Deterministic seeds per building/component; do not repeat the same six-route graph.','shape':'Piecewise angular walks with irregular kink spacing; initial kink spacing 2–8% of component short dimension, lateral offset 0.5–2%. Branch widths 35–60% of parent.','spalls':'Sparse local edge wedges at 20–40% of qualifying endpoints; use 2–5x local mouth width, bounded by component thickness. Avoid uniformly cratering every junction.','depth':'Keep converging inward walls and variable valley depth; cap depth below 15% of solid thickness and under half of thin cladding thickness. Resolve thin-shell panels before applying volumetric cutters.','resolution':'Judge at the 1440-wide game camera. Hero paths roughly 1–3 pixels, fine routes may be subpixel; do not inflate every distant cut to force visibility.','materials':'Do not fracture pipes, ducts, steel Y supports, window frames, glass, or arbitrary metal cladding with the concrete preset. Brittle/metal identification in the illustration is uncertain; classify native components explicitly.','scope':'Background ruins, dome, and rubble have broken silhouettes rather than resolvable small crack inventories at this resolution. Treat them separately; no speculative microcrack budget.'},'integration_order':['Foreground warm right pier and left lower panels','Middle-right connected panels and window surrounds','Left sloped bays, sparse upper shell, service backing','Selective bearing-zone supports and mineral fascias','Separate pavement and rubble stages']}
(O/'crack-inventory.json').write_text(json.dumps(a,indent=2))
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 4vw}p{max-width:1050px}a{color:#efbc91}.region{display:grid;grid-template-columns:minmax(220px,34%) 1fr;gap:28px}img{max-width:100%;height:auto}dt{color:#efbc91}dd{margin:0 0 8px} @media(max-width:700px){.region{display:block}}'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>068 · Whole-scene crack inventory</title><style>{css}</style><header><h1>068 · Whole-scene crack inventory</h1><p>Final crack finish: <b>45% → 100% darkening</b>. The reference favors sparse, connected fractures with strong differences between component families. Below is a visible-region inventory and initial procedural estimates—not measured physical dimensions or a claim that every panel is concrete.</p><p><a href="#final">Final material proof</a> · <a href="/art/reviews/xenon-068/crack-inventory.json">Procedural inventory</a></p></header>'
for x in items:
 page+=f'<section class="region" id="{x["id"]}"><div><img src="/art/reviews/xenon-068/{x["id"]}.png" alt="Reference crop {x["title"]}"></div><div><h2>{x["title"]}</h2><p><b>Visible evidence:</b> {x["observed"]}</p><dl>'
 for label,key in [('Eligible components damaged','estimated_damaged_component_fraction'),('Paths per damaged component','paths'),('Path span / component dimension','path_span_fraction'),('Mouth width estimate (mm)','estimated_mouth_width_mm'),('Depth estimate (mm)','estimated_depth_mm'),('Edge flare × local width','edge_flare_multiplier')]:page+=f'<dt>{label}</dt><dd>{x[key]}</dd>'
 page+=f'</dl><p>{x["placement"]}</p></div></section>'
page+='<section><h2>Shared rules</h2>' + ''.join(f'<p><b>{k.title()}:</b> {v}</p>' for k,v in a['global_rules'].items()) +'<h2>Assembly order</h2><ol>'+''.join(f'<li>{v}</li>' for v in a['integration_order'])+'</ol><p>The atlas is the integration plan. Scene-wide cutters have not yet been placed; the two existing proof components now use the final material.</p></section><section id="final"><h2>Final 45% → 100% material</h2><a href="/art/reviews/xenon-068/final-panel.png"><img src="/art/reviews/xenon-068/final-panel.png" alt="Final crack material column proof"></a><p><a href="/art/reviews/xenon-068/final-support.png">Support proof</a> · <a href="/art/reviews/xenon-068/final-render.png">Alley camera</a> · <a href="/art/reviews/xenon-068/final.blend">Editable Blender scene</a></p></section></html>'
(R/'prototype/review-068.html').write_text(page);(R/'prototype/index.html').write_text(page)
