from pathlib import Path
from PIL import Image,ImageDraw
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-132';P='/art/studies/coliseum-132/'
labels=[v for v in ['selected','0x','2x','5x','10x'] if (O/v/'main-4k.png').exists()];roi=(1400,730,2510,1330)
for label in labels:
 d=O/label;im=Image.open(d/'main-4k.png').convert('RGB');im.resize((1440,1082),Image.Resampling.LANCZOS).save(d/'main.png');im.crop(roi).save(d/'street.png');im.crop(roi).convert('L').save(d/'gray.png')
contact=Image.new('RGB',(1110*2,640*((len(labels)+1)//2)),'#19191e');dr=ImageDraw.Draw(contact)
for i,label in enumerate(labels):
 x=(i%2)*1110;y=(i//2)*640;contact.paste(Image.open(O/label/'street.png'),(x,y+40));dr.text((x+15,y+12),'Selected 5x: full city span' if label=='selected' else ('Previous haze' if label=='0x' else label+' earlier span'),fill='white')
contact.save(O/'comparison.png')
style='''*{box-sizing:border-box}body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:30px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:10px 0}figcaption{margin:7px 0;color:#c5bbc4}button{background:#30292d;border:1px solid #78616a;color:#eee7df;border-radius:5px;padding:10px 20px;cursor:pointer;font:inherit}button[aria-pressed=true]{background:#76534c;border-color:#bd8b79}.controls{display:flex;gap:10px;flex-wrap:wrap;position:sticky;top:0;background:#19191eee;padding:10px 0;z-index:2}h1{font-size:32px}h2{font-size:24px;margin-top:40px}@media(max-width:700px){.grid{grid-template-columns:1fr}}'''
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>132 · Street haze gradient</title><style>{style}</style><h1>132 · Street haze gradient</h1><p>Selected direction: 5× haze at the coliseum, now increasing from the nearest skyscraper across the entire city stretch. The original strength studies remain available below. The haze still fades away upward by the second arcade.</p><div class="controls">'''
for label in labels:h+=f'<button id="b{label}" aria-pressed="{str(label==("selected" if "selected" in labels else "5x")).lower()}" onclick="choose(\'{label}\')">'+('Selected 5× · full city span' if label=='selected' else ('Previous haze' if label=='0x' else label.replace('x','×')+' · earlier span'))+'</button>'
h+=f'''</div><section id="street"><h2>Street-level view</h2><img id="streetim" src="{P}5x/street.png"></section><h2>Full scene</h2><img id="main" src="{P}5x/main.png"><p><a id="full" href="{P}5x/main-4k.png">Open selected 4K render</a> · <a id="scene" href="{P}5x/scene.blend">Editable scene</a></p><h2>Side by side</h2><div class="grid">'''
for label in labels:h+=f'<figure><img loading="lazy" src="{P}{label}/street.png"><figcaption>'+('Selected 5× · full city span' if label=='selected' else ('Previous haze' if label=='0x' else label.replace('x','×')+' · earlier span')+' far-end density')+'</figcaption></figure>'
h+='</div><details><summary>Grayscale comparison</summary><div class="grid">'
for label in labels:h+=f'<figure><img loading="lazy" src="{P}{label}/gray.png"><figcaption>{label}</figcaption></figure>'
h+=f'''</div></details><h2>Also included: final base geometry notes</h2><p>All comparison renders include the centered masonry joints above the arches and the higher bent framing connection.</p><div class="grid"><img src="/art/studies/coliseum-131/crown-joints/pilot-joint-detail.png"><img src="/art/studies/coliseum-131/frame/comparison-3x.png"></div><details><summary>Study settings and reference</summary><p>The selected version rises from25% density at the first skyscraper (48m) to5× at the coliseum (205m). Earlier2×/5×/10× studies began their rise deeper inside the city (80m) and are retained for comparison. These are local far-end density multipliers; perceived haze does not increase linearly. Color, height fade, lighting, camera, and surface materials are unchanged.</p><p><a href="/art/original/coliseum/coliseum.png">UCL-01: your original artwork, created with ChatGPT Images 2.5</a>. Supporting references: UCL-26 street-haze feedback and DP-03 atmospheric depth.</p></details><p>5× selected; full-city gradient corrected as requested. Centerpiece remains in review.</p><script>function choose(v){{document.getElementById('streetim').src='{P}'+v+'/street.png';document.getElementById('main').src='{P}'+v+'/main.png';document.getElementById('full').href='{P}'+v+'/main-4k.png';document.getElementById('scene').href='{P}'+v+'/scene.blend';for(const x of ['selected','0x','2x','5x','10x'])document.getElementById('b'+x)?.setAttribute('aria-pressed',x===v)}}</script></html>'''
if 'selected' in labels: h=h.replace('5x/street.png','selected/street.png',1).replace('5x/main.png','selected/main.png',1).replace('5x/main-4k.png','selected/main-4k.png',1).replace('5x/scene.blend','selected/scene.blend',1)
(R/'prototype/review-132.html').write_text(h)
