from pathlib import Path
from PIL import Image
import json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');O=R/'art/reviews/xenon-055';P=R/'prototype'
css='''*{box-sizing:border-box}body{margin:0;background:#19181e;color:#eee7df;font:16px system-ui}header,section{padding:24px 3vw}p{max-width:1000px;line-height:1.6;color:#c9c1c9}a{color:#efbc91}button{padding:10px 16px;background:#38313e;color:#eee;border:1px solid #79637a;border-radius:6px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.trio{grid-template-columns:1fr 1fr 1fr}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid{grid-template-columns:1fr}}'''
def fig(path,cap):return f'<figure><a href="{path}" target="_blank"><img src="{path}" alt="{cap}"></a><figcaption>{cap}</figcaption></figure>'
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Chamfers, highlights and surface texture · 055</title><style>{css}</style><header><h1>Chamfers, highlights and surface texture · 055</h1><p>Walkway fascias now have an actual 45° folded face, giving the long highlight a geometric home. Window kicks and selected structural corners receive their own restrained highlights. Pipe bands are brighter. Facade materials add fine tonal grain, sparse chips and short connected scar fragments.</p><p><a href="#alley">Whole alley</a> · <a href="#detail">High-resolution detail</a> · <a href="#reference">Column reference</a> · <a href="../art/reviews/xenon-055/scene.blend">Blender scene</a> · <a href="../art/reviews/xenon-055/chamfered-gangway-kit.blend">Updated gangway kit</a> · <a href="review-054.html">Previous review</a></p><button onclick="document.body.classList.toggle('gray')">Toggle grayscale</button></header><section id="alley"><div class="grid">'''+fig('../art/reviews/xenon-054/render.png','054 · before')+fig('../art/reviews/xenon-055/render.png','055 · geometry-supported highlight strips')+'</div></section>'
page+='<section id="detail"><h2>Same camera · high-resolution surface detail</h2><p>Native render crops at three times the preview resolution, not enlarged preview pixels. Compare the long fascia chamfer, angled window panels and the fine surface marks.</p><div class="grid">'+fig('../art/reviews/xenon-055/054-surface-detail.png','054 · previous surface')+fig('../art/reviews/xenon-055/055-surface-detail.png','055 · highlights and finer surface vocabulary')+'</div></section>'
page+='<section id="reference"><h2>Reference direction</h2><div class="grid">'+fig('../art/reviews/xenon-055/user-column.png','Your column closeup · tonal fields, damage scales and corner strip')+fig('../art/reviews/xenon-051/reference-facade.png','Selected concept · walkway highlight and architectural detail')+'</div><p>The new 90 mm chamfer has equal run and rise. Highlights respond to actual face orientation and retain local warm/cool pigment. Grain, isolated chips and connected scar fragments remain distinct layers. Connected fragments are color wear, not new structural crack geometry.</p></section><section><h2>Preserved</h2><p>Camera, alley scale, sky and the accepted metal/facade palettes. Pipe geometry and prior physical spalls remain intact. New geometry is limited to walkway fascia cross-sections and narrow structural blade chamfers. Supporting reference IDs: DP-08 (Darius Puia), HM-03 (Heavy Metal, 1981), AF-06 (Peter Chung / MTV); source credits remain in the earlier reviews.</p></section></html>'
(P/'index.html').write_text(page);(P/'review-055.html').write_text(page)
