from pathlib import Path
from PIL import Image
import json,numpy as np
R=Path(__file__).resolve().parents[1];O=R/'art/studies/city-106';baseline=Image.open(R/'art/studies/scrap-105/main.png').convert('RGB');roi=(520,245,980,505)
baseline.crop(roi).resize((1380,780),Image.Resampling.LANCZOS).save(O/'before-city.png');checks={}
for v in ['A','B','C']:
 im=Image.open(O/v/'main.png').convert('RGB');im.crop(roi).resize((1380,780),Image.Resampling.LANCZOS).save(O/v/'city.png');im.convert('L').crop(roi).resize((1380,780),Image.Resampling.LANCZOS).save(O/v/'gray.png')
 d=np.abs(np.asarray(im).astype(int)-np.asarray(baseline).astype(int));checks[v]={'road_mean_change':float(d[560:880,420:1000].mean()),'road_max_change':int(d[560:880,420:1000].max())}
for n in ['before','after']:
 im=Image.open(O/('magenta-'+n+'.png')).convert('RGB');im.resize((1380,780),Image.Resampling.NEAREST).save(O/('magenta-'+n+'-large.png'))
 a=np.asarray(im);mask=(a[:,:,0]>250)&(a[:,:,1]<5)&(a[:,:,2]>250)
 checks['magenta_'+n]={'left_join_pixels':int(mask[155:215,10:65].sum()),'right_join_pixels':int(mask[145:220,375:445].sum())}
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>106 · City depth and painted detail</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1440px;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}figure{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{margin:40px 0}button{padding:11px 16px;font:inherit;background:#36333d;color:white;border:1px solid #81716c;cursor:pointer;border-radius:5px}button.active{background:#89624c}figcaption{padding:8px 0;color:#c5bbc4}summary{cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>106 · City depth and painted detail</h1><p>The grey-and-purple pair is now deep on the right: behind all other city buildings and in front of the brown tower. Four outer-front buildings bridge the near and far streets.</p><p><a href="#density">Brush density</a> · <a href="#visibility">Magenta visibility test</a> · <a href="#placement">Placement comparison</a></p><p>The three variants share placement, colors, mark sizes and a nested set of brush strokes. Feathering softens the ends along one axis while retaining squared side edges.</p>'''
labels={'A':'A · 2× brush marks','B':'B · 4× brush marks','C':'C · Dense brush marks (8×)'}
for v,label in labels.items():s+=f'<button id="{v}" class="{("active" if v=="A" else "")}" onclick="show(\'{v}\')">{label}</button> '
s+='''<p id="caption">A · 2× brush marks</p><a id="full-link" href="/art/studies/city-106/A/main.png"><img id="main" src="/art/studies/city-106/A/main.png"></a><section id="density"><h2>Painted detail at the same camera</h2>'''
for v,label in labels.items():
 count=sum(x['strokes'] for x in json.loads((O/v/'marks.json').read_text()));s+=f'<figure><a href="/art/studies/city-106/{v}/city.png"><img src="/art/studies/city-106/{v}/city.png"></a><figcaption>{label} · {count} marks across the visible native tower set · <a href="/art/studies/city-106/{v}/scene.blend">Editable scene</a></figcaption></figure>'
s+='''<p>The dense treatment approaches the earlier window-grid coverage, using irregular painted marks rather than rows.</p></section><section id="visibility"><h2>Magenta visibility test</h2><p>The sky, clouds, distant dust volume and mountainous structure are removed in this diagnostic only. Exposed background is solid #ff00ff. The road opening and upper skyline remain intentionally open.</p><div class="grid"><figure><img src="/art/studies/city-106/magenta-before-large.png"><figcaption>Before · gaps at the outer joins</figcaption></figure><figure><img src="/art/studies/city-106/magenta-after-large.png"><figcaption>After · additional frontage closes the outer joins</figcaption></figure></div></section><section id="placement"><h2>Placement comparison</h2><div class="grid"><figure><img src="/art/studies/city-106/before-city.png"><figcaption>105 · Previous placement</figcaption></figure><figure><img src="/art/studies/city-106/A/city.png"><figcaption>106 · Corrected deep pair and outer frontage, with 2× detail</figcaption></figure></div></section><details><summary>Grayscale density comparison</summary>'''
for v in labels:s+=f'<figure><img src="/art/studies/city-106/{v}/gray.png"><figcaption>{labels[v]}</figcaption></figure>'
s+='''</details><script>const labels={A:'A · 2× brush marks',B:'B · 4× brush marks',C:'C · Dense brush marks (8×)'};function show(v){const p='/art/studies/city-106/'+v+'/main.png';document.getElementById('main').src=p;document.getElementById('full-link').href=p;document.getElementById('caption').textContent=labels[v];for(const k of ['A','B','C'])document.getElementById(k).classList.toggle('active',k===v);}</script></html>'''
(R/'prototype/review-106.html').write_text(s);(R/'prototype/index.html').write_text(s)
