from pathlib import Path
R=Path(__file__).resolve().parents[1];A='/art/studies/soil-094/'
def fig(path,label):return f'<figure><a href="{path}"><img src="{path}" loading="lazy" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>094 · More painted flecks</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>094 · More painted flecks</h1><p>All three build on 093C. Its sponge texture and broad brushwork are fixed; only scattered pigment flecks increase. Fleck size, color and contrast stay the same.</p><p><a href="#close">Closeups</a> · <a href="#A">A · a bit more</a> · <a href="#B">B · moderately more</a> · <a href="#C">C · way more</a></p>'''
s+='<section id="close"><h2>Same patch, increasing flecks</h2><div class="grid">'+fig('/art/studies/soil-093/detail-C.png','Baseline · 093C')+fig(A+'detail-A.png','A · a bit more')+fig(A+'detail-B.png','B · moderately more')+fig(A+'detail-C.png','C · way more, deliberately heavy')+'</div></section>'
for key,title,desc in [('A','A bit more','110,000 total flecks: about 1.3× the fleck count in the previous fleck-heavy 093A.'),('B','Moderately more','170,000 total flecks: 2× the fleck count in 093A.'),('C','Way more','340,000 total flecks: 4× the fleck count in 093A. Deliberately tests the upper limit.')]:
 s+=f'<section id="{key}"><h2>{key} · {title}</h2><p>{desc} All retain the same 1,400 sponge dabs from 093C.</p>'+fig(A+f'main-{key}.png',f'{key} · main camera')+f'<p><a href="{A}scene-{key}.blend">Editable Blender scene {key}</a></p></section>'
s+='<p>Counts refer to pigment marks across the road material, not individual visible pixels. Added marks are nested: each stronger version retains the previous level’s marks. <a href="'+A+'pigment-audit.json">Pigment audit</a>.</p></html>'
(R/'prototype/review-094.html').write_text(s);(R/'prototype/index.html').write_text(s)
