from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/soil-093';A='/art/studies/soil-093/'
Image.open(R/'art/studies/soil-092/detail-B.png').crop((58,130,806,606)).save(O/'baseline-detail.png')
def fig(path,label):return f'<figure><a href="{path}"><img src="{path}" loading="lazy" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>093 · Painted flecks and sponge texture</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>093 · Painted flecks and sponge texture</h1><p>Three high-frequency pigment treatments over the selected 092B broad brushwork. Same terrain, rocks, camera and underlying palette.</p><p><a href="#close">Closeup comparison</a> · <a href="#A">A · flecks</a> · <a href="#B">B · sponge</a> · <a href="#C">C · mixed</a></p>'''
s+='<section id="close"><h2>Same patch, same scale</h2><div class="grid">'+fig(A+'baseline-detail.png','Baseline · selected 092B')+fig(A+'detail-A.png','A · scattered pigment flecks')+fig(A+'detail-B.png','B · porous sponge clusters')+fig(A+'detail-C.png','C · flecks and sponge combined')+'</div><p>Click any image for its full-size crop. Texture density varies across irregular groups, with quiet areas between them.</p></section>'
for key,title,desc in [('A','Pigment flecks','Fine angular ochre and umber marks, with occasional larger fragments of pigment. About 15% of texture pixels receive marks.'),('B','Sponge texture','Porous dabs made from uneven clusters of small pigment marks. More open spaces between groups; about 9% coverage.'),('C','Mixed texture','Scattered flecks combined with porous clusters. About 13% coverage; a balance of individual marks and connected texture.')]:
 s+=f'<section id="{key}"><h2>{key} · {title}</h2><p>{desc}</p>'+fig(A+f'main-{key}.png',f'{key} · main camera')+f'<p><a href="{A}scene-{key}.blend">Editable Blender scene {key}</a></p></section>'
s+='<p>Coverage describes the world-space pigment map, not screen-area coverage. All variants add color marks rather than surface bumps. Mean RGB shifts are below one 8-bit level. <a href="'+A+'pigment-audit.json">Pigment audit</a>.</p></html>'
(R/'prototype/review-093.html').write_text(s);(R/'prototype/index.html').write_text(s)
