from pathlib import Path
from PIL import Image
import json,re,urllib.request
R=Path(__file__).resolve().parents[1];O=R/'art/studies/alley-weathering-146';P='/art/studies/alley-weathering-146/';B='/art/studies/alley-weathering-145/'
for n in ['combined-4k','before-4k']:
 p=O/f'combined/{n}.png';im=Image.open(p).convert('RGB');im.resize((1800,round(im.height*1800/im.width)),Image.Resampling.LANCZOS).save(p.with_name(n+'-display.png'))
actual=(O/'actual/main-4k.png').exists();asec=''
if actual:
 audit=json.loads((O/'actual/placement-audit.json').read_text());box=tuple(map(int,audit['crop_bounds']))
 for name,src in [('before',R/'art/studies/alley-weathering-145/actual/main-4k.png'),('after',O/'actual/main-4k.png')]:
  im=Image.open(src).convert('RGB');im.crop(box).save(O/f'actual/{name}-crop.png');im.resize((1800,round(im.height*1800/im.width)),Image.Resampling.LANCZOS).save(O/f'actual/{name}-display.png')
 asec=f'<section id="alley"><h2>At the alley camera</h2><div class="pair"><figure><img src="{P}actual/before-crop.png"><figcaption>145</figcaption></figure><figure><img src="{P}actual/after-crop.png"><figcaption>146 · longer fading runoff and finer coating detail</figcaption></figure></div><details><summary>Full scene</summary><img src="{P}actual/after-display.png"></details><p><a href="{P}actual/main-4k.png">Native 4K scene</a> · <a href="{P}actual/scene.blend">Editable scene candidate</a></p></section>'
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>146 · Layered weathering</title><style>body{{background:#191a20;color:#eee6dd;font:17px/1.55 system-ui;max-width:1600px;margin:30px auto;padding:0 24px}}h1,h2{{font-weight:600}}p{{max-width:940px}}a{{color:#edbb98}}nav{{display:flex;gap:20px;flex-wrap:wrap;margin:20px 0 30px}}img{{display:block;width:100%;height:auto}}figure{{margin:12px 0}}figcaption{{color:#c2b7b1;font-size:15px}}.pair{{display:grid;grid-template-columns:1fr 1fr;gap:24px}}button{{background:#443c42;color:#fff;border:1px solid #80716d;border-radius:5px;padding:10px 18px;font:inherit;cursor:pointer}}section{{margin:48px 0}}details{{margin:22px 0}}summary{{cursor:pointer}}@media(max-width:760px){{.pair{{grid-template-columns:1fr}}}}</style>
<h1>146 · Layered weathering</h1><p>The lightening mask now combines broad areas across panels with fine, irregular splotches concentrated toward their bottoms. Rust keeps a darker origin and gains a translucent second layer that reaches 50% farther, fading down the surface.</p><nav><a href="#study">Combined study</a><a href="#mask">Lightening mask</a><a href="#rust">Longer runoff</a>{'<a href="#alley">Alley placement</a>'if actual else ''}<a href="/prototype/review-145.html#reference">Reference</a></nav>
<section id="study"><button onclick="document.getElementById('hero').src='{P}combined/combined-4k-display.png'">146 · Updated</button> <button onclick="document.getElementById('hero').src='{B}combined/combined-4k-display.png'">145 · Previous</button><img id="hero" src="{P}combined/combined-4k-display.png"><p><a href="{P}combined/combined-4k.png">Native 4K component render</a> · <a href="{P}combined/panel-kit.blend">Editable panel kit</a></p></section>
<section id="mask"><h2>Broad areas and fine splotches</h2><div class="pair"><figure><img src="{B}material/key-left.png"><figcaption>145 · broad response</figcaption></figure><figure><img src="{P}material/key-left.png"><figcaption>146 · broad response plus detail weighted toward each panel’s base</figcaption></figure></div><p>The broad field continues across seams. Finer patches follow each panel’s bottom edge, with quieter upper interiors. Warmth responds to the lighting; cool fill can still pick up a restrained lightening response.</p><details><summary>Moved-light and cool-fill controls</summary><div class="pair"><figure><img src="{P}material/key-right.png"><figcaption>Warm light moved right</figcaption></figure><figure><img src="{P}material/cool-fill-only.png"><figcaption>Cool fill only</figcaption></figure></div></details></section>
<section id="rust"><h2>Longer, fading runoff</h2><div class="pair"><figure><img src="{P}details/before.png"><figcaption>145 · original dark runs</figcaption></figure><figure><img src="{P}details/after.png"><figcaption>146 · separate translucent wash extends their reach by 50%</figcaption></figure></div><p>The second layer tapers and loses opacity as it descends. Its strength and reach remain independently editable.</p></section>{asec}<details><summary>Geometry control</summary><img src="{P}combined/clay.png"></details><p>Working study toward the full weathering target; not a finished rollout or final approval.</p></html>'''
p=R/'prototype/review-146.html';p.write_text(h);links=re.findall(r'(?:src|href)="(/[^"#]+)"',h);missing=[q for q in links if not(R/q.lstrip('/')).exists()];assert not missing,missing
(O/'publication-check.json').write_text(json.dumps({'missing':missing,'http':urllib.request.urlopen('http://127.0.0.1:8765/prototype/review-146.html').status,'actual_scene_included':actual},indent=2));print('Published146')
