from pathlib import Path
from PIL import Image
import json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');O=R/'art/reviews/xenon-057';P=R/'prototype'
for stage in ['055','057']:
 im=Image.open(R/f'art/reviews/xenon-{stage}/render.png')
 for part,box in [('pipes',(280,120,560,670)),('facade',(1050,30,1440,550))]:im.crop(box).save(O/f'{stage}-{part}.png')
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}p{max-width:950px;color:#c9c1c9}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.trio{grid-template-columns:repeat(3,1fr)}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}button{padding:10px;background:#38313e;color:white;border:1px solid #79637a}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
a='/art/reviews/xenon-057/'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>057 · Surface texture across the alley</title><style>{css}</style><header><h1>057 · Surface texture across the alley</h1><p>The approved tonal-island treatment now runs across architecture and services. Round metal pipes are more neutral gray, while the blue and warm facade palettes retain their identity. Texture strength varies by material, with a lighter treatment on distant structures.</p><p><a href="#pipes">Pipes</a> · <a href="#facade">Facades</a> · <a href="#detail">Native closeup</a> · <a href="{a}scene.blend">Editable scene</a> · <a href="surface-study-056.html">Isolated proof 056</a></p><button onclick="document.body.classList.toggle(\'gray\')">Toggle grayscale</button></header><section><div class="grid">'+fig('/art/reviews/xenon-055/render.png','055 · Before')+fig(a+'render.png','057 · Tonal texture + neutral round metal')+'</div></section>'
for part in ['pipes','facade']:
 page+=f'<section id="{part}"><h2>{part.title()} · scene-scale comparison</h2><div class="grid trio">'+fig('/art/reviews/xenon-051/reference-'+part+'.png','Selected concept')+fig(a+'055-'+part+'.png','055 · Before')+fig(a+'057-'+part+'.png','057 · After')+'</div></section>'
page+='<section id="detail"><h2>Native high-resolution facade detail</h2><p>Rendered at three times the preview resolution from the same camera.</p><div class="grid">'+fig('/art/reviews/xenon-055/055-surface-detail.png','055 · Before')+fig(a+'facade-detail.png','057 · Connected interior texture')+'</div></section><section><h2>Surface reference</h2><div class="grid">'+fig('/references/user-pipe-surface-study/pipe-detail-fine-geometry-and-weathering.png','UP-03 · User-supplied material target')+fig(a+'pipes-detail.png','057 · Native pipe detail')+'</div><p>References: UP-01, UP-02, UP-03 and DP-08. The illustrative references are comparison targets; every new scene image is rendered directly from editable Blender materials and geometry.</p><p>Geometry, camera, sky and existing damage are preserved. Surface treatment is procedural and varies with position in the scene. User review pending.</p></section></html>'
(P/'review-057.html').write_text(page);(P/'index.html').write_text(page)
