from pathlib import Path
R=Path('/PATH/TO/transmissions-from-alpha-centauri');P=R/'prototype';a='/art/reviews/xenon-064/'
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}p{max-width:950px;color:#c9c1c9}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>064 · Surface material continued into cracks</title><style>{css}</style><header><h1>064 · Surface material continued into cracks</h1><p>The crack walls now use the host’s existing weathered surface material. Procedural position sampling is projected back to the original face plane, carrying the paint and wear pattern down into the opening. Actual crack normals still shape the shading. The inherited finish makes these cuts subtler than the separate dark fill; this comparison tests material continuity.</p><p><a href="#panel">Column face</a> · <a href="#support">Support</a> · <a href="{a}scene.blend">Editable scene</a></p></header>'
for part in ['panel','support']:
 page+=f'<section id="{part}"><h2>{"Mineral column face" if part=="panel" else "Concrete support"}</h2><div class="grid">'+fig('/art/reviews/xenon-062/'+part+'.png','062 · separate dark mineral fill')+fig(a+part+'.png','064 · original surface material continued inward')+'</div></section>'
page+='<section><h2>Game camera</h2>'+fig(a+'render.png','064 · unchanged geometry, depth and camera')+'</section><section><p>This supersedes the unreviewed 063 gray-material lightening. The material is procedural, not an image projection. Physical reflection remains confined to the opening lip. References: UP-01, UP-03, DP-08 and the supplied concrete closeup. User review pending.</p></section></html>'
(P/'review-064.html').write_text(page);(P/'index.html').write_text(page)
