from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/city-101'
for v,box,size in [('A',(551,262,936,482),(746,366)),('B',(550,306,951,481),(674,282))]:
 im=Image.open(O/v/'main.png');im.crop(box).resize((size[0]*2,size[1]*2)).save(O/v/'matched-city.png');im.convert('L').save(O/v/'grayscale.png')
s='''<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>101 · Two reference layouts</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}figure{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}section{margin:35px 0}button{padding:12px;font:inherit;background:#45404a;color:white;border:1px solid #88776b;cursor:pointer}figcaption{padding:8px 0}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>101 · Two reference layouts</h1><p>Two measured layout studies: individual building heights, roof profiles and sampled colors fitted to the visible alley opening, with low foreground blocks exposing the city behind. The road may wind through the buildings; rubble-skyscraper damage remains a later pass.</p><p><a href="#A">A · Original pixel art</a> · <a href="#B">B · Painted reference</a></p>'''
for k,label,path in [('baseline','100 · Continuous street','/art/studies/city-100/main.png'),('A','A · Original pixel art','/art/studies/city-101/A/main.png'),('B','B · Painted reference','/art/studies/city-101/B/main.png')]:s+=f'<button onclick="document.getElementById(\'main\').src=\'{path}\';document.getElementById(\'label\').textContent=\'{label}\'">{label}</button> '
s+='<p id="label">B · Painted reference</p><img id="main" src="/art/studies/city-101/B/main.png">'
for v,title,ref,desc in [('A','Original pixel-art layout','original-city-layout.png','28 visible masses; four central buildings omitted. Darker purple and mauve blocks with abrupt height changes.'),('B','Painted reference layout','painted-city-layout.png','31 visible masses; nested towers and low frontages, with a route allowed to bend between them.')]:
 s+=f'<section id="{v}"><h2>{v} · {title}</h2><p>{desc}</p><div class="grid"><figure><img src="/references/user-city-study/{ref}"><figcaption>Supplied reference</figcaption></figure><figure><a href="/art/studies/city-101/{v}/matched-city.png"><img src="/art/studies/city-101/{v}/matched-city.png"></a><figcaption>Native geometry · corresponding view</figcaption></figure></div><p><a href="/art/studies/city-101/{v}/scene.blend">Editable {v} scene</a></p></section>'
s+='<p>Visible profiles and colors are measured approximations. Soft pixels and occlusion limit exact boundaries; hidden footprints and depth are inferred. These compare layout and palette, with intact native architecture rather than the references’ later-stage destruction. The approved foreground, rocks, soil, sky and landmark are preserved.</p></html>'
(R/'prototype/review-101.html').write_text(s);(R/'prototype/index.html').write_text(s)
