from pathlib import Path
import json,html
R=Path('/PATH/TO/transmissions-from-alpha-centauri');P=R/'prototype';O=R/'art/reviews/xenon-050'
if not (P/'review-049.html').exists():(P/'review-049.html').write_text((P/'index.html').read_text())
style='''*{box-sizing:border-box}body{margin:0;background:#19181e;color:#eee7df;font:16px system-ui}header,section{padding:24px 3vw}h1{font-size:32px;margin:0 0 12px}h2{font-size:22px}section{scroll-margin-top:90px}p{max-width:1000px;color:#c8c1c5;line-height:1.6}a{color:#edbb8e}button,select{font:inherit;padding:9px 12px;background:#302c37;color:#eee;border:1px solid #716273;border-radius:6px;cursor:pointer}.controls{display:flex;gap:14px;flex-wrap:wrap;align-items:center;position:sticky;top:0;background:#19181ef2;padding:12px 3vw;z-index:2}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#24212b;padding:10px}img,svg{width:100%;display:block}figcaption{padding:10px 2px 2px}small{color:#bbb0bb}.gray img,.gray svg{filter:grayscale(1)}.compare{position:relative;overflow:hidden}.compare>img{width:100%}.compare .overlay{position:absolute;inset:0;clip-path:inset(0 50% 0 0)}input[type=range]{width:250px}details{margin:18px 0}table{border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid #45404c}@media(max-width:800px){.grid{grid-template-columns:1fr}}'''
paths={'baseline':'../art/reviews/xenon-049/render.png',**{k:f'../art/reviews/xenon-050/{k}.png' for k in ['cel','painted','hybrid']}}
labels={'baseline':'049 · PBR control','cel':'050 A · Graphic cel','painted':'050 B · Painted transitions','hybrid':'050 C · Hybrid'}
def fig(k):return f'<figure><a href="{paths[k]}" target="_blank"><img src="{paths[k]}" alt="{labels[k]}"></a><figcaption>{labels[k]}</figcaption></figure>'
def crop(path,box):return f'<svg viewBox="{box}" role="img" aria-label="Matching game-camera detail"><image href="{path}" width="1440" height="1080"/></svg>'
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Final style studies · 050</title><style>{style}</style><header><h1>From rendered surfaces to drawn architecture</h1><p>Three native Blender treatments of the exact same alley. Geometry, coating, cracks, spalls and runoff are preserved. Only shading, directional shadow softness and line treatment change. These are look-development studies, not approved final art.</p><p><a href="#comparison">Wipe comparison</a> · <a href="#variants">All three treatments</a> · <a href="#details">Identical closeups</a> · <a href="#references">Reference art</a> · <a href="review-049.html">Previous review</a></p></header><div class="controls"><label>Treatment <select id="pick"><option value="hybrid">C · Hybrid</option><option value="painted">B · Painted transitions</option><option value="cel">A · Graphic cel</option></select></label><button id="gray">Toggle grayscale</button><label>Before / after <input id="wipe" type="range" min="0" max="100" value="50"></label><a id="blend" href="../art/reviews/xenon-050/hybrid.blend">Open Blender scene</a></div><section id="comparison"><h2>Same camera · PBR on the left, selected treatment on the right</h2><div class="compare"><img class="candidate" src="{paths['hybrid']}" alt="Selected style study"><img class="overlay" src="{paths['baseline']}" alt="049 PBR control"></div></section><section id="variants"><h2>Compare the treatments</h2><div class="grid">{''.join(fig(k) for k in ['baseline','cel','painted','hybrid'])}</div><p>A tests discrete tones. B keeps gentle transitions. C holds broad tones with narrow shadow transitions. All use fine structural lines plus stronger contours; distant lines fade. C also adds local contact shading in recesses.</p></section><section id="details"><h2>At the game camera · matching details</h2>'''
for name,box in [('Pipes and mounting hardware','280 135 310 470'),('Windows and coating','1090 0 350 370'),('Concrete support and panel damage','1040 360 380 390')]:
 page+=f'<h3>{name}</h3><div class="grid"><figure>{crop(paths["baseline"],box)}<figcaption>049 · PBR control</figcaption></figure><figure class="detail">{crop(paths["hybrid"],box)}<figcaption>Selected treatment</figcaption></figure></div>'
page+='</section><section id="references"><h2>Reference direction</h2><div class="grid"><figure><img src="../art/reviews/xenon-001/selected-third.png" alt="Selected concept target"><figcaption>Selected concept · broad value shapes and selective architectural drawing</figcaption></figure>'
manifest=json.loads((R/'references/manifest.json').read_text())
if isinstance(manifest,dict):manifest=manifest.get('references',manifest.get('images',[]))
for ident in ['DP-08','HM-03','AF-06']:
 ref=next(x for x in manifest if x['id']==ident)
 page+=f'<figure><img src="../references/{ref["file"]}" alt="{html.escape(ref["title"])}"><figcaption>{ident} · {html.escape(ref["creator"])}<br><small>Reference only · <a href="{html.escape(ref["source_page"])}">Source and credit</a></small></figcaption></figure>'
page+='''</div></section><section><h2>What this study establishes</h2><p>My provisional preference is C. The material patterns survive the change to flatter shading, but the linework is still mechanically uniform and deep recesses need stronger shadow grouping. This is a useful first style proof, with further work needed to reach the reference. Existing unfinished rubble, dome infill and the character proxy are unchanged and should not be mistaken for final assets.</p></section><script>
const paths='''+json.dumps(paths)+''';const pick=document.querySelector('#pick');pick.onchange=()=>{document.querySelector('.candidate').src=paths[pick.value];document.querySelectorAll('.detail image').forEach(e=>e.setAttribute('href',paths[pick.value]));document.querySelector('#blend').href='../art/reviews/xenon-050/'+pick.value+'.blend';};document.querySelector('#gray').onclick=()=>document.body.classList.toggle('gray');document.querySelector('#wipe').oninput=e=>document.querySelector('.overlay').style.clipPath='inset(0 '+(100-e.target.value)+'% 0 0)';</script></html>'''
(P/'style-study-050.html').write_text(page);(P/'index.html').write_text(page)
