from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/reviews/xenon-079';im=Image.open(O/'render.png');ref=Image.open(R/'art/reviews/xenon-001/selected-third.png')
regions=[('road',(300,650,1150,880),(300,700,1150,920)),('soil',(925,470,1440,770),(990,660,1448,930)),('scrap',(0,865,1440,1080),(0,900,1448,1086)),('distance',(485,290,955,505),(320,410,1100,800)),('sky',(450,0,950,150),(370,0,920,175))]
for name,a,b in regions:im.crop(a).save(O/(name+'.png'));ref.crop(b).save(O/('reference-'+name+'.png'))
style="body{background:#19191e;color:#eee7df;font:17px/1.6 system-ui;margin:30px}a{color:#efbc91}img{width:100%;display:block}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0}section{margin:36px 0}figcaption{padding:8px 0}table{border-collapse:collapse}td,th{text-align:left;padding:8px;border-bottom:1px solid #555}@media(max-width:800px){.grid{grid-template-columns:1fr}}"
s=f"<!doctype html><html lang='en'><meta charset='utf-8'><title>079 · Reference-grounded environment</title><style>{style}</style><h1>079 · Reference-grounded environment</h1><p>Creator–critic refinements to road fractures and grit, soil-aware stones, rust-washed scrap, distant debris, skyline color, cloud edges and selective architectural highlights. Coliseum excluded.</p><p><a href='#comparison'>Before / after</a> · <a href='#road'>Road</a> · <a href='#soil'>Soil</a> · <a href='#scrap'>Scrap</a> · <a href='#distance'>Distance</a> · <a href='#sky'>Sky</a> · <a href='/art/reviews/xenon-079/scene.blend'>Editable Blender scene</a></p><img src='/art/reviews/xenon-079/render.png'><section id='comparison' class='grid'><figure><img src='/art/reviews/xenon-075/render.png'><figcaption>075 baseline</figcaption></figure><figure><img src='/art/reviews/xenon-079/render.png'><figcaption>079 candidate</figcaption></figure></section>"
for name,a,b in regions:s+=f"<section id='{name}'><h2>{name.title()} closeups</h2><div class='grid'><figure><img src='/art/reviews/xenon-079/reference-{name}.png'><figcaption>Selected concept · reference region</figcaption></figure><figure><img src='/art/reviews/xenon-079/{name}.png'><figcaption>Native render · comparable region</figcaption></figure></div></section>"
s+="<section><h2>Critic ledger</h2><p>Qualitative 0–100 assessments, not objective similarity scores or user approval.</p><table><tr><th>Target</th><th>Earlier</th><th>Latest assessment</th></tr><tr><td>Far-building palette</td><td>69</td><td>85</td></tr><tr><td>Cloud boundary shapes</td><td>74</td><td>84</td></tr><tr><td>Near-scrap highlight structure</td><td>78</td><td>84</td></tr><tr><td>End-rubble morphology</td><td>75</td><td>78–82 across closeup / whole-frame reviews</td></tr><tr><td>Directional earth pattern</td><td>63</td><td>79 final</td></tr><tr><td>Footing-stone integration</td><td>76</td><td>79</td></tr></table><p>Remaining tradeoffs: earth-bank irregularity, how quiet the soil interiors should stay, and the warmth of the near pile. No claim that every axis is above 80.</p></section>"
s+="<p>Closeups are semantic region comparisons, not pixel registration. Agent assessments are not user approval. Earlier rejected passes remain saved.</p></html>"
(R/'prototype/review-079.html').write_text(s);(R/'prototype/index.html').write_text(s)
