from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');P=R/'prototype';O=R/'art/reviews/xenon-062';a='/art/reviews/xenon-062/'
x=np.array(Image.open(O/'panel.png').convert('RGB'),dtype=float);y=np.array(Image.open(O/'panel-no-spec.png').convert('RGB'),dtype=float);d=np.max(abs(x-y),axis=2);metrics={'max_channel_difference_8bit':float(d.max()),'pixels_changed_more_than_2_levels':int((d>2).sum()),'total_pixels':int(d.size),'mean_absolute_channel_difference':float(np.mean(abs(x-y)))};(O/'specular-check.json').write_text(json.dumps(metrics,indent=2))
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}p{max-width:950px;color:#c9c1c9}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>062 · Light-responsive crack lips</title><style>{css}</style><header><h1>062 · Light-responsive crack lips</h1><p>The broad beige treatment is removed. Crack interiors are dark matte mineral; physical dielectric specular fades out within 1.2 mm of the mouth. Geometry, depth and the scene lighting are unchanged.</p><p><a href="#support">Support</a> · <a href="#panel">Column face</a> · <a href="#specular">Specular check</a> · <a href="{a}scene.blend">Editable scene</a></p></header>'
for part in ['support','panel']:
 page+=f'<section id="{part}"><h2>{"Concrete support" if part=="support" else "Mineral column face"}</h2><div class="grid">'+fig('/art/reviews/xenon-061/'+part+'.png','061 · broad beige lit faces')+fig(a+part+'.png','062 · matte interior, narrow reflective lip')+'</div></section>'
page+='<section id="specular"><h2>Same scene and camera · specular on / off</h2><p>Only the fracture material’s specular strength changes between these images. There is no emission ramp or painted highlight on the new fracture material. Click for full resolution.</p><div class="grid">'+fig(a+'panel.png','062 · mouth specular enabled')+fig(a+'panel-no-spec.png','Control · specular disabled')+f'</div><p>{metrics["pixels_changed_more_than_2_levels"]:,} pixels differ by more than 2 display levels. This measures the isolated rendered contribution, not an artistic quality score.</p></section><section><h2>Game camera</h2>'+fig(a+'render.png','062 · unchanged geometry and layout')+'</section><section><p>Reference direction: UP-01, UP-03, DP-08 and the supplied concrete closeup. The 061 untextured geometry proof still applies. User review pending.</p></section></html>'
(P/'review-062.html').write_text(page);(P/'index.html').write_text(page)
print(json.dumps(metrics))
