from pathlib import Path
from PIL import Image,ImageChops,ImageEnhance
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/lines-095';A='/art/studies/lines-095/'
before=Image.open(R/'art/studies/soil-094/main-C.png').convert('RGB');after=Image.open(O/'main-structural.png').convert('RGB')
for label,box in [('footing',(1010,535,1110,609)),('contacts',(884,475,1150,615))]:
 for key,im in [('before',before),('after',after)]:im.crop(box).resize(((box[2]-box[0])*4,(box[3]-box[1])*4)).save(O/f'{label}-{key}.png')
def fig(path,label):return f'<figure><a href="{path}"><img src="{path}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>095 · Intersection ink</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}button{padding:12px;font:inherit;color:#eee;background:#45404a;border:1px solid #88776b;cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>095 · Ink at intersections</h1><p>094C soil is locked. This study adds visible lines where separate surfaces cross, preserving the approved geometry and materials.</p><p><a href="#footing">Footing</a> · <a href="#main">Main camera</a> · <a href="#details">Small details</a> · <a href="#proof">Native proof</a></p>'''
s+='<section id="footing"><h2>Buried footing · same camera pixels enlarged</h2><div class="grid">'+fig(A+'footing-before.png','Before · mesh outlines only')+fig(A+'footing-after.png','After · intersection ink added')+'</div></section>'
s+='<section id="main"><h2>Structural contacts</h2><p>Seven footing sources, with nearby geometry included to hide occluded lines. Click to switch the same main-camera image.</p><button onclick="let i=document.getElementById(\'mainimage\');let a=i.dataset.after===\'yes\';i.src=a?\'/art/studies/soil-094/main-C.png\':\'/art/studies/lines-095/main-structural.png\';i.dataset.after=a?\'no\':\'yes\';this.textContent=a?\'Before · click for intersection ink\':\'After · click for baseline\'">After · click for baseline</button><img id="mainimage" data-after="yes" src="'+A+'main-structural.png"><p><a href="'+A+'scene-structural.blend">Editable structural proof</a></p></section>'
s+='<section id="details"><h2>Expanded detail tests</h2><p>Small rubble receives new ground-contact lines. The weathering trial inks geometric crack boundaries; pigment flecks, stains and color patches keep their existing treatment. Detail cameras isolate the difference with the usual Freestyle pass disabled in both images; the main-camera comparison retains normal scene outlines.</p>'
for stem,title in [('details-rocks','Small rubble · added ground contact ink'),('details-weather','Geometric weathering · added crack boundary ink')]:
 if (O/f'{stem}-before.png').exists() and (O/f'{stem}-after.png').exists():s+='<h3>'+title+'</h3><div class="grid">'+fig(A+stem+'-before.png','Before')+fig(A+stem+'-after.png','Additional ink')+'</div>'
if (O/'main-expanded.png').exists():
 s+='<h3>Expanded sample at the main camera</h3><p>Adds contact ink to 12 near-road rocks and material-boundary ink to one cracked facade panel. This is a representative test, not a scene-wide rollout.</p><button onclick="let i=document.getElementById(\'expanded\');let a=i.dataset.after===\'yes\';i.src=a?\'/art/studies/lines-095/main-structural.png\':\'/art/studies/lines-095/main-expanded.png\';i.dataset.after=a?\'no\':\'yes\';this.textContent=a?\'Structural only · click for expanded\':\'Expanded detail ink · click for structural only\'">Expanded detail ink · click for structural only</button><img id="expanded" data-after="yes" src="'+A+'main-expanded.png"><p><a href="'+A+'scene-expanded.blend">Editable expanded study</a></p>'
s+='<h3>Near-road sample at scene scale, enlarged</h3><div class="grid">'+fig(A+'rocks-main-before.png','Existing outlines')+fig(A+'rocks-main-after.png','With additional contact ink')+'</div>'
s+='</section><section id="proof"><h2>Isolated native intersection proof</h2>'+fig(A+'probe.png','Only actual visible face intersections receive strokes; ordinary silhouette edges are disabled in this proof.')+'<p>The scene keeps its existing outlines and adds Blender Line Art intersection strokes. Hidden intersections are excluded. Material-only weathering needs a separate contour treatment because colors do not create intersecting geometry. These baked strokes are camera-dependent and regenerate when the camera changes. <a href="https://docs.blender.org/manual/it/5.2/grease_pencil/modifiers/generate/line_art.html">Blender Line Art documentation</a>.</p></section></html>'
(R/'prototype/review-095.html').write_text(s)
