from pathlib import Path
import json
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/soil-081';ref=json.loads((O/'reference-statistics.json').read_text());cand=json.loads((O/'candidate-statistics.json').read_text());url='/art/studies/soil-081/'
style='body{background:#19191e;color:#eee7df;font:17px/1.6 system-ui;margin:30px}a{color:#efbc91}img{width:100%;display:block}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.three{grid-template-columns:repeat(3,1fr)}figure{margin:0}section{margin:40px 0}figcaption{padding:8px}table{border-collapse:collapse}td,th{padding:10px;text-align:left;border-bottom:1px solid #555}.swatch{display:inline-block;padding:25px 12px;margin:3px;color:white}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(file,caption):return f'<figure><a href="{url+file}"><img src="{url+file}"></a><figcaption>{caption}</figcaption></figure>'
s=f'<!doctype html><html lang="en"><meta charset="utf-8"><title>081 · Soil pigment and crack junctions</title><style>{style}</style><h1>081 · Soil pigment and crack junctions</h1><p>Three native material treatments keep the calibrated brown family while testing finer, more discrete grain. The new direction prioritizes a 90s adventure-game surface over matching the softness of an enlarged screenshot. Rocks are unchanged.</p><p><a href="#grain">Grain closeups</a> · <a href="#camera">Alley camera</a> · <a href="#junction">Crack junction</a> · <a href="#palette">Palette measurements</a></p>'
s+='<section><h2>C · Integrated material and repaired junctions</h2><p>Calibrated discrete grain on the full scene, with existing lip geometry clipped at crack crossings. Native audit: 0 surface samples over crack voids; no lost lip objects. <a href="/art/studies/soil-081/selected-scene.blend">Editable scene</a> · <a href="/art/studies/soil-081/junction-audit.json">Geometry audit</a></p>'+fig('selected-main.png','Selected candidate · rocks and architecture preserved')+'</section>'
s+='<section id="grain"><h2>Grain at the same close camera</h2><p>Each native view spans 3.625m horizontally at 1370×746. Discrete grain is anchored to the ground in 1.25cm cells; the image itself is not pixelated.</p><div class="grid three">'+''.join(fig(v+'-clean.png',t) for v,t in [('soft','A · broad soft blend — prior direction'),('fine','B · fine continuous pigment'),('discrete','C · discrete six-color grains')])+'</div></section>'
s+='<section id="camera"><h2>At the alley camera</h2><p>Material-only tests on the 079 scene. Existing rocks, architecture, sky and scene cracks are preserved; the junction repair below is still an isolated generator proof.</p><div class="grid three">'+''.join(fig(v+'-main.png',v.title()) for v in ['soft','fine','discrete'])+'</div></section>'
s+='<section id="junction"><h2>Actual clipped crack junction</h2><p>All lip geometry is now cut by every crack void. The shared opening remains continuous where cracks cross. Width follows the sampled opening; narrow tapered lips avoid detached rectangular strips.</p><div class="grid">'+fig('junction.png','Native material')+fig('junction-clay.png','Clay topology — no highlight bridges across missing soil')+fig('junction-grazing.png','Same geometry under grazing light — specular response stays on remaining lips')+'</div></section>'
s+='<section><h2>Matched texture crops</h2><p>Each crop is 260×120 native image pixels, displayed at equal size.</p><div class="grid">'+fig('reference-clean.png','Reference crack-free crop')+fig('discrete-crop.png','C native crop at the matched close view')+'</div></section>'
s+='<section id="palette"><h2>Reference palette</h2><div class="grid"><figure><img src="/references/user-soil-study/dark-soil-detail.png"><figcaption>US-01 · user supplied reference</figcaption></figure>'+fig('reference-clean.png','Crack-free reference region: x900–1160, y450–570; original 260×120 pixels.')+'</div><p>Native grain variant measurements: <a href="/art/studies/soil-081/variant-statistics.json">RGB quantiles and scale diagnostics</a>.</p><p>Lossless RGB/count histogram: <a href="'+url+'reference-full-palette.json">full palette dump</a>. <a href="'+url+'reference-statistics.json">Quantiles and spatial diagnostics</a>.</p>'
for c in [(68,48,41),(73,52,44),(77,55,46),(80,58,48),(84,61,50),(90,65,53)]:s+=f'<span class="swatch" style="background:rgb{c}">{c}</span>'
s+='<table><tr><th>Measurement</th><th>Reference</th><th>Initial calibrated smooth study</th></tr>'
for key in ['mean_rgb','std_rgb','luma_std']:
 def fmt(x):return ', '.join(f'{v:.2f}' for v in x) if isinstance(x,list) else f'{x:.2f}'
 s+=f'<tr><td>{key}</td><td>{fmt(ref[key])}</td><td>{fmt(cand[key])}</td></tr>'
s+='</table><p>Initial clean-material critic: palette91, tonalrange89, spatialscale84, distribution82. These scores describe the earlier smooth study, not approval of the new grain variants. Junction clipping:90. The full histogram remains a diagnostic; no reference image is used as a scene texture.</p></section></html>'
(R/'prototype/soil-study-081.html').write_text(s)
