from pathlib import Path
R=Path(__file__).resolve().parents[1];A='/art/studies/rocks-090/'
def fig(name,label):return f'<figure><a href="{A}{name}"><img src="{A}{name}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>090 · Fractured rocks and debris</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>090 · Fractured rocks and debris</h1><p>New unequal fracture-plane masters replace the old cube-like stones: low wedges, broad slabs, shards, occasional chunks and thin splinters. Placement follows the actual soil surface with partial burial. The final ground palette and painted treatment are still a later pass.</p><p><a href="#reference">Reference closeups</a> · <a href="#catalog">Native shape catalogue</a> · <a href="#detail">In-scene detail</a> · <a href="/art/studies/rocks-090/scene.blend">Blender scene</a></p>'''
s+=fig('main.png','New scatter on the accepted 089 soil geometry')
s+='<section id="reference"><h2>What the reference rocks are doing</h2><div class="grid">'+fig('reference-road.png','Road · small low wedges, off-center ridges, partly buried bases')+fig('reference-right.png','Foundations · elongated inclined slabs, broad faces, clipped corners')+'</div><p>Enlarged crops from the project’s selected concept reference. Larger fragments gather near walls; smaller chips spread across the pale soil and thin out into the road.</p></section>'
s+='<section id="catalog"><h2>Native geometry catalogue</h2>'+fig('catalog.png','Fifteen examples · broad unequal facets and selective corner fractures')+'<p>Five families: wedge, slab, shard, chunk and splinter. All masters are closed editable meshes. <a href="'+A+'catalog.blend">Open the catalogue in Blender</a>.</p></section>'
s+='<section id="detail"><h2>Road and foundation detail</h2>'+fig('road-detail.png','Same alley camera at twice resolution · simple temporary rock shading')+'</section><section><h2>Placed geometry in neutral clay</h2>'+fig('placement-clay.png','Actual terrain and rocks · neutral physical lighting')+'</section></html>'
(R/'prototype/review-090.html').write_text(s);(R/'prototype/index.html').write_text(s)
