from pathlib import Path
R=Path(__file__).resolve().parents[1];A='/art/studies/soil-092/'
def fig(path,label):return f'<figure><a href="{path}"><img src="{path}" loading="lazy" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>092 · Painted soil and grounded foundation rocks</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>092 · Painted soil and grounded foundation rocks</h1><p>The 120 road stones are locked. Foundation fragments now rest on broad bases fitted to the actual soil surface. The approved terrain mesh is unchanged.</p><p><a href="#A">A · quiet wash</a> · <a href="#B">B · stronger brushwork</a> · <a href="#detail">Soil closeups</a> · <a href="#contact">Foundation contact</a> · <a href="#reference">Painting approach</a></p>'''
for label,title in [('A','Quiet wash'),('B','Stronger brushwork')]:
 s+=f'<section id="{label}"><h2>{label} · {title}</h2>'+fig(A+f'main-{label}.png','Same heightmap, camera and approved road stones')+f'<p><a href="{A}scene-{label}.blend">Editable Blender scene {label}</a></p></section>'
s+='<section id="detail"><h2>Soil at close range</h2><div class="grid">'+fig(A+'detail-A.png','A · subordinate pigment strokes')+fig(A+'detail-B.png','B · more distinct contiguous strokes')+'</div><h2>Previous treatment</h2>'+fig('/art/studies/rocks-091/main.png','091 · previous fine relief shading')+'</section>'
s+='<section id="contact"><h2>Broad, stable rock contact</h2>'+fig('/art/studies/foundation-092/contact.png','Contact proof · foundation bases seated on native terrain')+'<p>238 bank rocks adjusted; all 120 road rocks preserved. Terrain fitting replaces arbitrary tilt, with shallow embedding and tightened bank contact accents. <a href="'+A+'contact-audit.json">Contact audit</a>.</p></section>'
s+='<section id="reference"><h2>How to paint the soil</h2><p>Start with a restrained ground-color wash. Group illumination into broad connected shapes. Drag broken pigment marks through selected ruts and ridges, then add small flecks unevenly. Quiet areas are part of the texture.</p><p>Here, filtered slopes from the approved heightmap guide the tonal wash. Explicit irregular stroke clusters add pigment, while fine grain stays subordinate. The world-space material is generated from our own terrain and brush primitives; no reference image is applied to the geometry.</p>'+fig('https://i.pinimg.com/736x/7a/1b/a0/7a1ba0a794a785078f58dcdf72b4e45e.jpg','User-supplied animation background reference · connected washes and selective dragged marks')+'</section></html>'
(R/'prototype/review-092.html').write_text(s);(R/'prototype/index.html').write_text(s)
