from pathlib import Path
import json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');O=R/'art/reviews/xenon-053';P=R/'prototype';data=json.loads((O/'metrics.json').read_text())
css='''*{box-sizing:border-box}body{margin:0;background:#19181e;color:#eee7df;font:16px system-ui}header,section{padding:24px 3vw}p{max-width:1060px;line-height:1.6;color:#c9c1c9}a{color:#efbc91}button,select{padding:10px 16px;background:#38313e;color:#eee;border:1px solid #79637a;border-radius:6px;font:inherit;cursor:pointer}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.trio{grid-template-columns:1fr 1fr 1fr}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}.gray img{filter:grayscale(1)}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px;text-align:right;border-bottom:1px solid #45404c}th:first-child,td:first-child{text-align:left}.controls{position:sticky;top:0;background:#19181ef5;padding:12px 3vw;z-index:2;display:flex;gap:12px;align-items:center}section{scroll-margin-top:80px}.scroll{overflow:auto}@media(max-width:800px){.grid{grid-template-columns:1fr}}'''
def fig(path,cap,cl=''):return f'<figure><a href="{path}" target="_blank"><img class="{cl}" src="{path}" alt="{cap}"></a><figcaption>{cap}</figcaption></figure>'
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Measured style variants · 053</title><style>{css}</style><header><h1>Measured style variants · 053</h1><p>The approved 052 palette is the starting point. These three treatments explore saturation, contrast, line darkness and finite runoff visibility. Geometry and camera are identical.</p><p><a href="#facade">Facade</a> · <a href="#pipes">Pipes</a> · <a href="#statistics">Measurements</a> · <a href="#alley">Full renders</a> · <a href="review-052.html">Previous review</a></p></header><div class="controls"><label>Variant <select id="pick"><option value="A">A · Restrained</option><option value="B">B · Graphic contrast</option><option value="C" selected>C · Weathered balance</option></select></label><button id="gray">Toggle grayscale</button><a id="scene" href="../art/reviews/xenon-053/C.blend">Blender scene</a></div>'''
for region in ['facade','pipes']:
 page+=f'<section id="{region}"><h2>{region.title()} · reference / baseline / selected variant</h2><div class="grid trio">'+fig('../art/reviews/xenon-051/reference-'+region+'.png','Selected concept · reference')+fig('../art/reviews/xenon-053/052-'+region+'.png','052 · baseline')+fig('../art/reviews/xenon-053/C-'+region+'.png','Selected variant',region)+'</div></section>'
page+='<section id="statistics"><h2>What the pixels tell us</h2><p>Each crop is resized to 600 px tall with its aspect ratio preserved. Comparable subject matter is used, but the images are not geometrically registered. Values describe these crops—not the entire artwork. More is not always better.</p>'
labels={'median_saturation':'Median HSV saturation','p90_saturation':'90th-percentile saturation','linear_luminance_std':'Linear-light luminance spread','display_p90_p10':'Display luminance P90−P10','dark_area_pct':'Dark area (%)','dark_line_pct':'Local dark-line proxy (%)','edge_pct':'Strong edge coverage (%)','vertical_chromatic_band_rms':'Vertical chromatic-band proxy','fine_detail_rms':'Fine-detail energy'}
for region,values in data['regions'].items():
 page+=f'<h3>{region.title()}</h3><div class="scroll"><table><thead><tr><th>Measure</th>'+''.join('<th>'+x+'</th>' for x in ['Reference','052','A','B','C'])+'</tr></thead><tbody>'
 for key,label in labels.items():
  page+='<tr><td>'+label+'</td>'+''.join('<td>'+f'{values[k][key]:.3f}'+'</td>' if k in values else '<td>Pending</td>' for k in ['reference','052','A','B','C'])+'</tr>'
 page+='</tbody></table></div>'
page+='''<p><strong>How to read these:</strong> Saturation measures channel separation. Contrast uses both linear-light spread and a robust display-value range. The dark-line proxy counts locally dark pixels below a brightness threshold, distinguishing some linework from broad shadows. Fine-detail energy measures small-scale luminance changes.</p><p><strong>The vertical-band number is not a rain detector.</strong> It measures red–blue variation coherent along the vertical direction while excluding very dark pixels and strong luminance edges. Panel boundaries and geometry still contribute. The reference facade scores lower than the baseline here, despite visibly richer weathering; the pipe crop shows the opposite. Use it with the closeups, never as a score to maximize.</p><p><a href="../art/reviews/xenon-053/metrics.json">Full measurements and limitations</a></p></section><section id="alley"><h2>Three artistic directions</h2><p>A makes the smallest change. B emphasizes graphic contrast and black drawing. C prioritizes readable chromatic runoff with intermediate contrast. Runoff remains finite and seam-fed; services retain their separate wear.</p><div class="grid">'''
page+=fig('../art/reviews/xenon-052/render.png','052 · control')
for k,title in [('A','Restrained'),('B','Graphic contrast'),('C','Weathered balance')]:page+=fig('../art/reviews/xenon-053/'+k+'.png',k+' · '+title)
page+='''</div></section><section><h2>Reference provenance</h2><p>The cropped selected concept is the established visual target. Supporting references: <a href="../references/darius-puia/DP-08-layered-infrastructure.jpg">DP-08 · Darius Puia / BakaArts</a>, HM-03 · Heavy Metal (1981), AF-06 · Peter Chung / MTV. Creator credits and source links remain in the preceding reference reviews. References are not incorporated into the materials.</p></section><script>document.querySelector('#gray').onclick=()=>document.body.classList.toggle('gray');document.querySelector('#pick').onchange=e=>{for(const r of ['facade','pipes']){const im=document.querySelector('img.'+r);im.src='../art/reviews/xenon-053/'+e.target.value+'-'+r+'.png';im.parentElement.href=im.src;}document.querySelector('#scene').href='../art/reviews/xenon-053/'+e.target.value+'.blend';};</script></html>'''
(P/'index.html').write_text(page);(P/'review-053.html').write_text(page)
