from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-110'
for name,path in [('before',R/'art/studies/coliseum-109/A/main.png'),('after',O/'main.png')]:
 im=Image.open(path).convert('RGB');im.crop((480,110,960,440)).resize((1440,990),Image.Resampling.LANCZOS).save(O/(name+'-detail.png'));im.convert('L').save(O/(name+'-gray.png'))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>110 · Coliseum front ruin</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1440px;margin:32px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}figure{margin:28px 0}figcaption{color:#c5bbc4;padding:8px 0}section{margin:40px 0}</style><h1>110 · Coliseum front ruin</h1><p>Reference-A framing, rear half removed. Inward-battered towers and a modest forward lean create convergence without a sideways roll. Deep arcades, layered masonry, broken crown, painted weathering and local ink are native editable scene elements.</p><p><a href="#detail">Before / after</a> · <a href="#bay">Bay proof</a> · <a href="#reference">Reference</a> · <a href="/art/studies/coliseum-110/scene.blend">Editable scene</a> · <a href="/art/studies/coliseum-110/main-4k.png">4K render</a></p><img src="/art/studies/coliseum-110/main.png"><section id="detail"><h2>From scale study to detailed ruin</h2><figure><img src="/art/studies/coliseum-110/before-detail.png"><figcaption>109A · Original scale study with rear wall</figcaption></figure><figure><img src="/art/studies/coliseum-110/after-detail.png"><figcaption>110 · Open rear, converging front structure and material detail</figcaption></figure></section>'''
if (O/'bay-painted.png').exists():s+='<section id="bay"><h2>Isolated native bay proof</h2><img src="/art/studies/coliseum-110/bay-painted.png"><p>Closer inspection camera and neutral background; geometry and materials are editable.</p><h2>Same bay, untextured</h2><img src="/art/studies/coliseum-110/bay-clay.png"></section>'
s+='''<section id="reference"><h2>Selected reference · UCL-01</h2><img src="/references/user-coliseum/structure-crop.png"><p>Original project artwork, created by the project creator using ChatGPT Images 2.5. Enlarged for analysis only. Hidden construction and physical tilt are inferred from the visible forms.</p></section><details><summary>Grayscale comparison</summary><img src="/art/studies/coliseum-110/before-gray.png"><img src="/art/studies/coliseum-110/after-gray.png"></details><p>The closer physical placement preserves the selected projected framing while shortening the haze path; the locked city and atmosphere are unchanged. This is a centerpiece candidate for review, not an approved final.</p></html>'''
(R/'prototype/review-110.html').write_text(s);(R/'prototype/index.html').write_text(s)
