from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-129';p='/art/studies/coliseum-129/'
regions={'detail':(1350,320,2690,1230),'arches':(1780,560,2120,940),'pillars':(1655,670,2185,995),'cornice':(1810,740,1990,830)}
for label,path in [('before',R/'art/studies/coliseum-128/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB')
 for name,box in regions.items():im.crop(box).save(O/(label+'-'+name+'.png'))
 im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/(label+'-main.png'))
 im.crop(regions['detail']).convert('L').save(O/(label+'-gray.png'))
 if label=='after':im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/'main.png')
style='''*{box-sizing:border-box}body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:32px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:18px 0}figcaption{color:#c5bbc4;margin-top:7px}button{background:#30292d;border:1px solid #78616a;color:#eee7df;border-radius:5px;padding:9px 18px;cursor:pointer;font:inherit}button[aria-pressed=true]{background:#76534c;border-color:#bd8b79}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}h1{font-size:32px;line-height:1.2}h2{font-size:24px;margin-top:44px}details{margin:32px 0}summary{cursor:pointer}@media(max-width:800px){.pair{grid-template-columns:1fr}}'''
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>129 · Stronger arches and consistent pillars</title><style>{style}</style><h1>129 · Stronger arches and consistent pillars</h1><p>Arch stones are 75% thicker inward, with their outer edges held fixed. The smaller arched pillar inset repeats across matching shafts. Cornice supports are about 20% lighter, with clear breaks above the round-column capitals. Softer shading on stone joint ends removes the long dark spokes around the arches.</p><p><a href="#detail">Detail comparison</a> · <a href="#arches">Arch stones</a> · <a href="#pillars">Pillar insets</a> · <a href="#cornice">Column clearance</a> · <a href="{p}main-4k.png">4K render</a> · <a href="{p}scene.blend">Editable scene</a> · <a href="{p}kit.blend">Reusable kit</a></p><div class="controls"><button id="after" aria-pressed="true" onclick="choose('after')">129 · Current</button><button id="before" aria-pressed="false" onclick="choose('before')">128 · Previous</button></div><img id="main" src="{p}after-main.png">'''
for name,title in [('detail','Combined changes'),('arches','More substantial arch masonry'),('pillars','Consistent smaller arched insets'),('cornice','Clear space above the round columns')]:
 h+=f'<section id="{name}"><h2>{title}</h2><div class="pair"><figure><img src="{p}before-{name}.png"><figcaption>128</figcaption></figure><figure><img src="{p}after-{name}.png"><figcaption>129</figcaption></figure></div></section>'
h+=f'''<details><summary>Neutral geometry proof</summary><img src="{p}clay.png"></details><details><summary>Grayscale comparison</summary><div class="pair"><img src="{p}before-gray.png"><img src="{p}after-gray.png"></div></details><p>UCL-01 is your original artwork, created with ChatGPT Images 2.5. Its <a href="/art/original/coliseum/coliseum.png">original master</a> is stored with the project artwork and credited accordingly.</p><p>The coliseum remains in review. The accepted scene framing, sky, alley and road are preserved.</p><script>function choose(v){{document.getElementById('main').src='{p}'+v+'-main.png';for(const x of ['after','before'])document.getElementById(x).setAttribute('aria-pressed',x===v?'true':'false')}}</script></html>'''
(R/'prototype/review-129.html').write_text(h)
