from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-109'
for v in ['A','B']:
 im=Image.open(O/v/'main.png');im.convert('L').save(O/v/'gray.png');im.crop((450,0,1000,470)).resize((1100,940)).save(O/v/'detail.png')
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>109 · Coliseum scale</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1440px;margin:32px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}figure{margin:28px 0}button{padding:12px;background:#39333e;color:white;font:inherit;border:1px solid #88756d;cursor:pointer}figcaption{margin:8px 0}</style><h1>109 · Coliseum scale</h1><p>Two untextured structural studies. Both have three deep arcade levels, a complete open ring, floor bands, projecting towers and a preliminary broken upper wall. The camera and existing city remain fixed.</p><p>This review selects scale only. Fine masonry, refined damage, painted materials and final ink follow after selection.</p><button onclick="show('A')">A · Reference framing</button> <button onclick="show('B')">B · Mountainous</button><p id="caption">A · Reference framing</p><img id="main" src="/art/studies/coliseum-109/A/main.png"><p><a href="#both">Compare both</a> · <a href="#gray">Grayscale</a> · <a href="#reference">Selected reference</a></p><section id="both">'''
for v,title in [('A','Reference framing'),('B','Mountainous')]:s+=f'<figure><img src="/art/studies/coliseum-109/{v}/main.png"><figcaption>{v} · {title} · <a href="/art/studies/coliseum-109/{v}/scene.blend">Editable scene</a></figcaption></figure>'
s+='</section><section id="gray"><h2>Grayscale scale comparison</h2>'
for v in ['A','B']:s+=f'<figure><img src="/art/studies/coliseum-109/{v}/gray.png"><figcaption>{v}</figcaption></figure>'
s+='''</section><section id="reference"><h2>Selected reference · UCL-01</h2><img src="/references/user-coliseum/coliseum.png"><h2>Structure closeup</h2><img src="/references/user-coliseum/structure-crop.png"><p>User-supplied reference; original artwork by the project creator using ChatGPT Images 2.5. Original project artwork. Enlargement does not add source detail.</p></section><script>function show(v){document.getElementById('main').src='/art/studies/coliseum-109/'+v+'/main.png';document.getElementById('caption').textContent=v==='A'?'A · Reference framing':'B · Mountainous';}</script></html>'''
(R/'prototype/review-109.html').write_text(s);(R/'prototype/index.html').write_text(s)
