from pathlib import Path
import json
R=Path('/PATH/TO/transmissions-from-alpha-centauri');P=R/'prototype';O=R/'art/reviews/xenon-060';a='/art/reviews/xenon-060/'
css='body{margin:0;background:#19191e;color:#eee7df;font:16px/1.6 system-ui}header,section{padding:24px 3vw}p{max-width:950px;color:#c9c1c9}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:0;background:#24212b;padding:10px}img{display:block;width:100%}figcaption{padding:10px 0}button{padding:10px;background:#38313e;color:white;border:1px solid #79637a}.gray img{filter:grayscale(1)}@media(max-width:800px){.grid{grid-template-columns:1fr}}'
def fig(src,label):return f'<figure><a href="{src}"><img src="{src}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
page=f'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>060 · Real fracture lips and edge breakouts</title><style>{css}</style><header><h1>060 · Real fracture lips and edge breakouts</h1><p>The B network is rebuilt as a single closed cutter per component. Wider mouths slope into recessed floors, and openings flare where fractures reach the component boundary. Pale accents follow the normals of the new cut faces.</p><p><a href="#panel">Column face</a> · <a href="#support">Support</a> · <a href="#geometry">Untextured geometry</a> · <a href="{a}scene.blend">Editable scene</a> · <a href="review-059.html">059</a></p><button onclick="document.body.classList.toggle(\'gray\')">Toggle grayscale</button></header>'
for part,label in [('panel','Mineral column face'),('support','Concrete support')]:
 page+=f'<section id="{part}"><h2>{label}</h2><div class="grid">'+fig('/art/reviews/xenon-059/network-'+part+'.png','059 B · shallow grooves and dark floor meshes')+fig(a+part+'.png','060 · sloped fracture lips and flared exits')+'</div></section>'
page+='<section id="geometry"><h2>Geometry without painted depth cues</h2><p>The actual evaluated column mesh, lit with a neutral gray material. No crack pigment, separate dark floor strips, or line rendering. This view isolates the column to make the recesses visible.</p><div class="grid">'+fig(a+'panel-clay.png','060 · untextured geometry proof')+fig('/references/user-concrete-crack-study/concrete-fracture-reference.png','Reference · variable fracture mouths and edge loss')+'</div></section><section><h2>Game camera</h2>'+fig(a+'render.png','060 · two-component proof in the unchanged alley')+'<p>The candidate modifies geometry, not a projected image. Both evaluated components pass the closed-mesh audit with zero non-manifold edges. Floors are part of the cut surfaces; separate dark overlay meshes have been removed. The fracture lips vary in width, rather than applying a uniform bevel to every edge. Whole-scene coverage remains unchanged.</p></section></html>'
(P/'review-060.html').write_text(page);(P/'index.html').write_text(page)
