from pathlib import Path
import json
from PIL import Image, ImageOps
R=Path(__file__).resolve().parents[1];O=R/'art/studies/rocks-091';A='/art/studies/rocks-091/'
Image.open(O/'main.png').crop((536,627,585,665)).resize((490,380),Image.Resampling.NEAREST).save(O/'rock-closeup.png')
ImageOps.grayscale(Image.open(O/'main.png')).save(O/'grayscale.png')
def fig(path,caption):return f'<figure><a href="{path}"><img src="{path}" loading="lazy" alt="{caption}"></a><figcaption>{caption}</figcaption></figure>'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>091 · Rock distribution and painted facets</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}table{border-collapse:collapse}td,th{padding:8px 22px;text-align:left;border-bottom:1px solid #555}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>091 · Rock distribution and painted facets</h1><p>Reference-driven visible counts and scale, with warm lit faces, muted violet-brown flanks, broken pigment and dark ground contact. The accepted terrain geometry stays fixed.</p><p><a href="#counts">Count estimates</a> · <a href="#detail">Closeups</a> · <a href="#comparison">090 / 091</a> · <a href="/art/studies/rocks-091/scene.blend">Blender scene</a></p>'''
s+=fig(A+'main.png','091 · revised stones and foundation fragments')
audit=json.loads((O/'scatter-audit.json').read_text())
s+=f'<p>Placed candidates passing visibility checks: {audit["accepted_candidates"]["road"]} road · {audit["accepted_candidates"]["bank"]} foundation.</p>'
s+='<section id="counts"><h2>Count the visible stones, not just the objects</h2><table><tr><th>Region</th><th>Reference estimate</th><th>Generation target</th></tr><tr><td>Road</td><td>90–150 · midpoint 120</td><td>120</td></tr><tr><td>Foundation banks</td><td>180–300 · midpoint 240</td><td>240</td></tr></table><p>Manual estimates of recognizable stones at least 4 pixels wide in the 1448 × 1086 reference. Tiny soil grit, foreground scrap and the distant rubble pile are excluded. Larger stones: roughly 32 road wedges and 45 foundation anchors. The bank distribution favors the right side and irregular accumulations, with small fragments spread across the pale soil.</p><p>Generation checks camera visibility before placement; overlap, burial and final shading can still reduce the number you can distinguish in the finished render. <a href="'+A+'count-reference.json">Full estimate and uncertainty</a> · <a href="'+A+'scatter-audit.json">Placement audit</a>.</p></section>'
s+='<section id="detail"><h2>Rock surface treatment</h2><div class="grid">'+fig('/references/user-rock-study/rock-face-style.png','User-supplied target · warm top, purple-brown side, deep contact')+fig(A+'rock-closeup.png','091 · actual main-camera rock enlarged; no added detail')+'</div>'+fig(A+'detail.png','091 · enlarged road and foundation render')+fig('/art/studies/rocks-090/reference-road.png','Selected concept · road wedge distribution')+'<p>Measured target samples: lit face approximately #997260, side #403233, contact #201717. These are localized image samples rather than universal material colors. Native materials use directional face bands, irregular pigment losses and thin light-catching bevels; painted contact accents conform to the terrain. These accents are an artistic contact treatment, not ray-traced specular reflections.</p></section>'
s+='<section id="comparison"><h2>Same camera comparison</h2><div class="grid">'+fig('/art/studies/rocks-090/main.png','090 · geometry baseline')+fig(A+'main.png','091 · counts, placement and rock material')+'</div></section></html>'
(R/'prototype/review-091.html').write_text(s);(R/'prototype/index.html').write_text(s)
