from pathlib import Path
from PIL import Image
import json,re,urllib.request
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-173';P='/art/studies/coliseum-173/'
for label,path in [('before',R/'art/studies/coliseum-168/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/f'{label}-main.png');im.crop((1400,350,2460,1240)).save(O/f'{label}-landmark.png');im.crop((1665,435,2085,850)).save(O/f'{label}-crown.png');im.crop((1450,430,1650,640)).save(O/f'{label}-primary.png');im.crop((2065,540,2300,790)).save(O/f'{label}-secondary.png');im.resize((1800,1352),Image.Resampling.LANCZOS).save(O/f'{label}-display1800.png');im.resize((1440,1082)).convert('L').save(O/f'{label}-gray.png')
def pair(part):return f'<div class="pair"><figure><img src="{P}before-{part}.png"><figcaption>Before</figcaption></figure><figure><img src="{P}after-{part}.png"><figcaption>Updated</figcaption></figure></div>'
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>173 · Cooler sheltered masonry</title><style>body{{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:28px auto;padding:0 22px}}a{{color:#efbc91}}img{{width:100%;display:block}}.pair{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}figure{{margin:10px 0}}figcaption{{color:#c5bbc4}}button{{padding:12px;background:#433137;color:#fff;border:1px solid #957e77;cursor:pointer}}section{{margin:42px 0}}.close{{max-width:1000px}}@media(max-width:700px){{.pair{{grid-template-columns:1fr}}}}</style><h1>173 · Cooler sheltered masonry</h1><p>The existing broad weathered area shifts toward a cooler stone hue while retaining its brightness, texture and coverage. Warm facing remains alongside it.</p><button onclick="pick('after')">Updated</button> <button onclick="pick('before')">Before</button><img id="main" src="{P}after-main.png"><p><a href="{P}main-4k.png">Full 4K render</a> · <a href="{P}scene.blend">Editable scene</a> · <a href="{P}kit.blend">Colosseum kit</a></p><section id="crown" class="close"><h2>Broad sheltered facing</h2>{pair('crown')}</section><section id="detail" class="close"><h2>Left exposed core — preserved</h2>{pair('primary')}</section><section id="right" class="close"><h2>Cooler sheltered masonry</h2>{pair('secondary')}</section><section><h2>Whole landmark</h2>{pair('landmark')}</section><section><h2>Original reference</h2><img src="/art/studies/coliseum-134/analysis/independent/reference-display.png"><p>Your original artwork, created with ChatGPT Images 2.5.</p></section><details><summary>Grayscale</summary>{pair('gray')}</details><p id="status">Working candidate; user approval remains pending.</p><script>function pick(v){{document.getElementById('main').src='{P}'+v+'-main.png'}}</script></html>'''
h=h.replace('Broad sheltered facing','Broad sheltered facing').replace('<h2>Cooler sheltered masonry</h2>','<h2>Right-side damage and weathering — preserved</h2>')
if (O/'kit-proof/primary-painted.png').exists():
 h=h.replace('<section><h2>Original reference</h2>','<section><h2>Editable kit check</h2><p>The changed facing rendered from the saved kit, with its native contact ink.</p><div class="pair"><img src="'+P+'kit-proof/primary-painted.png"><img src="'+P+'kit-proof/primary-clay.png"></div></section><section><h2>Original reference</h2>')
if (O/'critic.json').exists():
 d=json.loads((O/'critic.json').read_text());sc=d.get('scores',{});h=h.replace('<p id="status">','<p>Independent scores: '+', '.join(k.replace('_',' ')+': '+str(v)for k,v in sc.items())+'.</p><p id="status">')
(R/'prototype/review-173.html').write_text(h);paths=re.findall(r'(?:src|href)="(/[^"#]+)"',h);missing=[p for p in paths if not(R/p.lstrip('/')).exists()];assert not missing,missing;(O/'delivery-check.json').write_text(json.dumps({'missing':missing,'resolution':list(Image.open(O/'main-4k.png').size),'http':urllib.request.urlopen('http://127.0.0.1:8765/prototype/review-173.html').status},indent=2));print('Published173')
