from pathlib import Path
from PIL import Image
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/coliseum-128';p='/art/studies/coliseum-128/'
regions={'detail':(1350,320,2690,1230),'arcade':(1420,595,2410,970),'pillar':(1990,690,2240,1000)}
for label,path in [('before',R/'art/studies/coliseum-127/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB')
 for name,box in regions.items():im.crop(box).save(O/(label+'-'+name+'.png'))
 im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/(label+'-main.png'))
 im.crop(regions['detail']).convert('L').save(O/(label+'-gray.png'))
 if label=='after':im.resize((1440,1082),Image.Resampling.LANCZOS).save(O/'main.png')
style='''*{box-sizing:border-box}body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;max-width:1500px;margin:32px auto;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}figure{margin:18px 0}figcaption{color:#c5bbc4;margin-top:7px}button{background:#30292d;border:1px solid #78616a;color:#eee7df;border-radius:5px;padding:9px 18px;cursor:pointer;font:inherit}button[aria-pressed=true]{background:#76534c;border-color:#bd8b79}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.ref{max-width:1000px}h1{font-size:32px;line-height:1.2}h2{font-size:24px;margin-top:44px}details{margin:32px 0}summary{cursor:pointer}@media(max-width:800px){.pair{grid-template-columns:1fr}}'''
h=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>128 · Even light, warmer masonry</title><style>{style}</style><h1>128 · Even light, warmer masonry</h1><p>The broad wall faces share a lighter dusty-red palette across the curve. Individual columns, arch interiors and ledges retain their shading, worn highlights and ink.</p><p><a href="#detail">Before / after</a> · <a href="#reference">Reference</a> · <a href="#gray">Grayscale</a> · <a href="{p}main-4k.png">4K render</a> · <a href="{p}scene.blend">Editable scene</a> · <a href="{p}kit.blend">Reusable kit</a></p><div class="controls"><button id="after" aria-pressed="true" onclick="choose('after')">128 · New lighting</button><button id="before" aria-pressed="false" onclick="choose('before')">127 · Previous</button></div><img id="main" src="{p}after-main.png" alt="Full scene with updated coliseum lighting"><section id="detail"><h2>Same geometry, gentler broad shading</h2><div class="pair"><figure><img src="{p}before-detail.png"><figcaption>127 · Broad violet-to-ochre gradient</figcaption></figure><figure><img src="{p}after-detail.png"><figcaption>128 · Warmer facade with local violet recesses</figcaption></figure></div></section><section id="reference"><h2>Reference and arcade detail</h2><figure class="ref"><img src="/references/user-coliseum/even-lighting-reference.png"><figcaption>Detail from your original artwork, created with ChatGPT Images 2.5.</figcaption></figure><figure class="ref"><img src="{p}after-arcade.png"><figcaption>128 · Native render crop</figcaption></figure></section><section id="gray"><h2>Light across the facade</h2><div class="pair"><figure><img src="{p}before-gray.png"><figcaption>Previous</figcaption></figure><figure><img src="{p}after-gray.png"><figcaption>Current</figcaption></figure></div></section><details><summary>First palette study</summary><div class="pair"><figure><img src="{p}lighting/A.png"><figcaption>A · Initial warmer stone</figcaption></figure><figure><img src="{p}lighting/B.png"><figcaption>B · Selected for this review: slightly redder, same brightness</figcaption></figure></div></details><p>4K comparison. Camera, geometry, scene lights, sky, haze, city and alley are preserved. This is a color and lighting revision; the centerpiece remains in review.</p><script>function choose(v){{document.getElementById('main').src='{p}'+v+'-main.png';for(const x of ['after','before'])document.getElementById(x).setAttribute('aria-pressed',x===v?'true':'false')}}</script></html>'''
(R/'prototype/review-128.html').write_text(h)
