from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/soil-083'
def fig(file,label):
 return f'<figure><a href="{file}"><img src="{file}" alt="{label}"></a><figcaption>{label}</figcaption></figure>'
a='/art/studies/soil-083/'
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>083 · Soil relief and painted light</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1450px;padding:0 22px}a{color:#efbc91}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}figure{margin:0}img{width:100%;display:block}figcaption{padding:9px 0}section{margin:38px 0}.crop img{max-width:520px;image-rendering:pixelated}table{border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid #555}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>083 · Soil relief and painted light</h1><p>Tiny clods, shallow irregular ridges and gathered soil form a height field. Lighting on that relief selects the brown palette, rather than painting a noise pattern directly into the color.</p><p><a href="#light">Light response</a> · <a href="#geometry">Geometry proof</a> · <a href="#palette">Reference detail</a> · <a href="#scene">Alley camera</a> · <a href="/prototype/soil-study-081.html">Earlier pigment study and crack repair</a></p>'''
s+='<section id="light"><h2>Same surface, two light directions</h2><div class="grid">'+fig(a+'A.png','Light A · native displaced soil')+fig(a+'B.png','Light B · same geometry and palette')+'</div></section>'
s+='<section id="geometry"><h2>The underlying relief</h2>'+fig(a+'clay.png','Untextured geometry: compacted patches, microclods, finite ridges and broader deposits')+'<p><a href="'+a+'scene.blend">Editable close-up Blender scene</a></p></section>'
s+='<section id="palette"><h2>Crack-free detail comparison</h2><div class="grid crop">'+fig('/art/studies/soil-081/reference-clean.png','US-01 · reference crop, enlarged pixels')+fig(a+'A-crop.png','Native relief crop, enlarged pixels')+'</div><p><a href="/references/user-soil-study/dark-soil-detail.png">Full supplied reference</a> · <a href="'+a+'statistics.json">Palette and light-response measurements</a></p></section>'
s+='<section id="scene"><h2>At the alley camera</h2>'+fig(a+'main.png','Scene-scale relief diagnostic')+'<p>The close-up uses displaced mesh geometry. At the alley camera, the same generated height field drives bump shading to retain tiny relief without rebuilding the cracked ground. Existing crack repairs, buildings and rocks are preserved. This remains a candidate for comparison with the earlier pigment-only treatment.</p><div class="grid">'+fig('/art/studies/soil-081/selected-main.png','081 · discrete pigment and repaired crack lips')+fig(a+'main.png','083 · relief-driven lighting')+'</div><p><a href="'+a+'main-scene.blend">Editable scene diagnostic</a></p></section>'
if (O/'review.json').exists():
 d=json.loads((O/'review.json').read_text());s+='<section><h2>Review notes</h2><p>'+d.get('summary','Experimental relief treatment; pending user review.')+'</p></section>'
s+='</html>'
(R/'prototype/soil-study-083.html').write_text(s)
