from pathlib import Path
from PIL import Image
import json,numpy as np
R=Path(__file__).resolve().parents[1];O=R/'art/studies/scrap-104';a=Image.open(R/'art/studies/city-103/main.png').convert('RGB');b=Image.open(O/'main.png').convert('RGB')
for name,im in [('before',a),('after',b)]:
 im.crop((0,835,1440,1082)).save(O/(name+'-pile.png'))
 im.crop((770,870,1110,1082)).resize((1020,636),Image.Resampling.LANCZOS).save(O/(name+'-detail.png'))
 im.convert('L').crop((0,835,1440,1082)).save(O/(name+'-gray.png'))
d=np.abs(np.asarray(a).astype(int)-np.asarray(b).astype(int));(O/'pixel-check.json').write_text(json.dumps({'locked_upper_scene_mean_rgb_change':float(d[:790].mean()),'locked_upper_scene_max_rgb_change':int(d[:790].max())},indent=2))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>104 · Warm light, blue steel</title><style>body{background:#19191e;color:#eee7df;font:17px/1.55 system-ui;margin:32px auto;max-width:1440px;padding:0 22px}a{color:#efbc91}img{width:100%;display:block}figure{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}section{margin:40px 0}button{padding:11px 16px;font:inherit;background:#36333d;color:white;border:1px solid #81716c;cursor:pointer;border-radius:5px}button.active{background:#89624c}figcaption{padding:8px 0;color:#c5bbc4}.ref{max-width:584px}summary{cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><h1>104 · Warm light, blue steel</h1><p>The scrap’s broad color now follows the lighting: warm rust on illuminated faces, slate-blue steel in shade. Fine pits and chipped highlight runs add wear without controlling the main color split.</p><p><a href="#pile">Pile comparison</a> · <a href="#detail">Closeups</a> · <a href="/art/studies/scrap-104/scene.blend">Editable scene</a></p><button id="old" onclick="show(false)">103 · Before</button> <button id="new" class="active" onclick="show(true)">104 · Lighting-driven palette</button><p id="caption">104 · Lighting-driven palette</p><a id="full-link" href="/art/studies/scrap-104/main.png"><img id="main" src="/art/studies/scrap-104/main.png"></a><section id="pile"><h2>Near-frame pile</h2><figure><img src="/art/studies/scrap-104/before-pile.png"><figcaption>Before · predominantly warm</figcaption></figure><figure><img src="/art/studies/scrap-104/after-pile.png"><figcaption>After · warm lit planes and blue shaded planes</figcaption></figure></section><section id="detail"><h2>Surface and highlight detail</h2><div class="grid"><figure><img src="/art/studies/scrap-104/before-detail.png"><figcaption>Before</figcaption></figure><figure><img src="/art/studies/scrap-104/after-detail.png"><figcaption>After · same camera crop</figcaption></figure></div><figure class="ref"><img src="/references/user-scrap-study/blue-rust-detail.png"><figcaption>Your supplied palette and surface reference</figcaption></figure></section><details><summary>Grayscale comparison</summary><img src="/art/studies/scrap-104/before-gray.png"><img src="/art/studies/scrap-104/after-gray.png"></details><script>function show(after){const p=after?'/art/studies/scrap-104/main.png':'/art/studies/city-103/main.png';document.getElementById('main').src=p;document.getElementById('full-link').href=p;document.getElementById('caption').textContent=after?'104 · Lighting-driven palette':'103 · Before';document.getElementById('old').classList.toggle('active',!after);document.getElementById('new').classList.toggle('active',after);}</script></html>'''
(R/'prototype/review-104.html').write_text(s);(R/'prototype/index.html').write_text(s)
