from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/road-characters-239';C=O/'comparison';C.mkdir(exist_ok=True)
for label,path in [('before',R/'art/studies/rubble-variation-237/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB')
 for name,box in [('road',(900,1250,2960,2460)),('characters',(1600,1720,2540,2420))]:im.crop(box).save(C/(label+'-'+name+'.png'))
 im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96)
b=np.asarray(Image.open(O/'main-4k.png').convert('RGB'));checks={}
for row in json.loads((R/'art/studies/pixel-characters-217/assets.json').read_text()):
 target=np.asarray(Image.open(R/row['placed_canvas']).convert('RGBA'));mask=target[:,:,3]==255;assert np.array_equal(b[mask],target[:,:,:3][mask]);checks[row['name']]='exact'
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
(R/'prototype/review-239.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>239 · Grounded characters and painted road</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:1500px;margin:auto;padding:24px}h1{font-size:25px}h2{font-size:20px;margin-top:36px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;margin:18px auto}#characters{max-width:940px}a{color:#e8c8a4}</style><main><h1>239 · Grounded characters and painted road</h1><p>Airam and Miranda retain their exact selected pixels, with shadows and soft boot contact grounding them. The road gains uneven compacted soil, warm dust and cooler mineral patches, with quieter texture in selected areas. The directional light now follows the final visible sun, with matching material lighting cues.</p><button onclick="choose('before',this)">Before · 237</button><button class="active" onclick="choose('after',this)">Road and shadows · 239</button><img id="full" src="../art/studies/road-characters-239/comparison/after-full.jpg" alt="Whole scene"><p><a href="../art/studies/road-characters-239/main-4k.png">Full-resolution scene</a> · <a href="../art/studies/road-characters-239/scene.blend">Editable scene</a></p><h2>Character grounding</h2><img id="characters" src="../art/studies/road-characters-239/comparison/after-characters.png" alt="Exact pixel characters with cast shadows"><h2>Road surface</h2><img id="road" src="../art/studies/road-characters-239/comparison/after-road.png" alt="Uneven painted road surface"></main><script>function choose(v,b){document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');for(let id of ['road','characters','full'])document.getElementById(id).src='../art/studies/road-characters-239/comparison/'+v+'-'+id+(id==='full'?'.jpg':'.png');location.hash=v}</script></html>''')
print('239 published; character pixels exact')
