from pathlib import Path
from PIL import Image
import numpy as np,json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/ruin-integration-235';C=O/'comparison';C.mkdir(exist_ok=True)
for label,path in [('before',R/'art/studies/far-weathering-234/main-4k.png'),('after',O/'main-4k.png')]:
 im=Image.open(path).convert('RGB');im.crop((3470,0,3840,1220)).save(C/(label+'-windows.png'));im.crop((2250,920,2690,1350)).save(C/(label+'-right.png'));im.crop((1100,650,2860,1490)).save(C/(label+'-street.png'));im.crop((1370,900,1700,1360)).save(C/(label+'-left.png'));im.resize((1920,1442),Image.Resampling.LANCZOS).save(C/(label+'-full.jpg'),quality=96)
b=np.asarray(Image.open(O/'main-4k.png').convert('RGB'));checks={}
for row in json.loads((R/'art/studies/pixel-characters-217/assets.json').read_text()):
 target=np.asarray(Image.open(R/row['placed_canvas']).convert('RGBA'));mask=target[:,:,3]==255;assert np.array_equal(b[mask],target[:,:,:3][mask]);checks[row['name']]='exact'
(O/'pixel-check.json').write_text(json.dumps(checks,indent=2))
(R/'prototype/review-235.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>235 · Layered ruins and window weathering</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}main{max-width:1500px;margin:auto;padding:24px}h1{font-size:25px}h2{font-size:20px;margin-top:36px}p{line-height:1.5;color:#c3bab4}button{background:#33303e;color:inherit;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;margin:18px auto}#windows{max-width:500px}#left,#right{max-width:900px}a{color:#e8c8a4}</style><main><h1>235 · Layered ruins and window weathering</h1><p>Broken walls gain interrupted construction joints, surviving slab fragments, larger facing losses and exposed cores. Quieter surface fields and finer interior ink separate structure from damage. The right-most near windows gain restrained rain residue, lower-pane buildup and subtle light-catching stains. Approved far towers are preserved.</p><button onclick="choose('before',this)">Before · 234</button><button class="active" onclick="choose('after',this)">Updated scene · 235</button><img id="street" src="../art/studies/ruin-integration-235/comparison/after-street.png" alt="Middle street comparison"><p><a href="../art/studies/ruin-integration-235/main-4k.png">Full-resolution scene</a> · <a href="../art/studies/ruin-integration-235/scene.blend">Editable scene</a> · <a href="../art/components/ruins/v235/ruined-walls.blend">Updated ruin library</a></p><h2>Left crumbling walls</h2><img id="left" src="../art/studies/ruin-integration-235/comparison/after-left.png" alt="Left crumbling walls"><h2>Right crumbling walls</h2><img id="right" src="../art/studies/ruin-integration-235/comparison/after-right.png" alt="Right crumbling walls"><h2>Near window weathering</h2><img id="windows" src="../art/studies/ruin-integration-235/comparison/after-windows.png" alt="Near right window weathering"><h2>Whole scene</h2><img id="full" src="../art/studies/ruin-integration-235/comparison/after-full.jpg" alt="Whole scene"></main><script>function choose(v,b){document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');for(let id of ['street','left','right','windows','full'])document.getElementById(id).src='../art/studies/ruin-integration-235/comparison/'+v+'-'+id+(id==='full'?'.jpg':'.png');location.hash=v}</script></html>''')
print('235 published; characters exact')
