from pathlib import Path
from PIL import Image,ImageOps
import json
R=Path(__file__).resolve().parents[1];O=R/'art/studies/scene-direction-218'
for label in ('current-sun','right-sun'):
 d=O/label;im=Image.open(d/'main-4k.png').convert('RGB');im.resize((1920,1442),Image.Resampling.LANCZOS).save(d/'display.jpg',quality=95)
 im.crop((500,0,3340,2360)).resize((1420,1180),Image.Resampling.LANCZOS).save(d/'landmark.jpg',quality=96)
 im.crop((1860,0,2700,750)).save(d/'sun.png')
 ImageOps.grayscale(im).resize((1440,1082)).save(d/'gray.jpg',quality=92)
p=R/'prototype/review-218.html'
p.write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>218 · Open alley and sun comparison</title><style>body{margin:0;background:#191820;color:#e4ded7;font:16px system-ui}header,main{max-width:1450px;margin:auto;padding:20px}h1{font-size:24px}p{line-height:1.5;color:#bfb7b3}button,a{color:inherit}button{background:#33303e;border:1px solid #777080;padding:12px 18px;border-radius:6px;cursor:pointer;margin:4px}button.active{background:#775347}img{display:block;width:100%;height:auto;background:#24212c}.pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}.pair img{width:100%}a{display:inline-block;margin:8px 15px 8px 0}figcaption{padding:8px 0}figure{margin:0}footer{padding:24px 0}</style><header><h1>218 · Open alley and sun comparison</h1><p>The selected 70% Colosseum scale and double-detail Traveler-A and Traveler-B sprites, with shorter, varied alley buildings. Compare the sun in its original position with a shift of one full visible diameter to the right. Lighting, sun size and height remain the same.</p><button class="active" onclick="choose('current-sun',this)">Original sun</button><button onclick="choose('right-sun',this)">Sun one diameter right</button></header><main><img id="scene" src="../art/studies/scene-direction-218/current-sun/display.jpg" alt="Combined scene with selected pixel characters and shorter alley architecture"><a id="full" href="../art/studies/scene-direction-218/current-sun/main-4k.png">Full-resolution image</a><a id="native" href="../art/studies/scene-direction-218/current-sun/scene.blend">Editable scene</a><p><a id="detail" href="../art/studies/scene-direction-218/current-sun/landmark.jpg">Landmark and street close-up</a></p><div class="pair"><figure><img src="../art/studies/scene-direction-218/current-sun/sun.png" alt="Original sun position"><figcaption>Original position</figcaption></figure><figure><img src="../art/studies/scene-direction-218/right-sun/sun.png" alt="Sun moved one diameter right"><figcaption>One diameter right</figcaption></figure></div><p>The character sprites are packed, editable 2D overlays using the exact selected pixels. Their placement is authored for this camera; they are not 3D characters.</p><footer><a href="review-210.html">Previous scale comparison</a><a href="review-212.html">Previous repeated alley</a><a href="review-214.html">Character treatments</a></footer></main><script>function choose(v,b){document.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let p='../art/studies/scene-direction-218/'+v+'/';document.getElementById('scene').src=p+'display.jpg';document.getElementById('full').href=p+'main-4k.png';document.getElementById('native').href=p+'scene.blend';document.getElementById('detail').href=p+'landmark.jpg';location.hash=v}if(location.hash==='#right-sun')choose('right-sun',document.querySelectorAll('button')[1]);</script></html>''')
print(p)
